### ISSUE TITLE
[Related Artists] X Works, X for sale line adjustment

### ISSUE THREAD

**Issue by briansw** [artsy/emission#106]
When the total number of works is equal to the total number for sale, simplify language to "X works for sale"

![screen shot 2016-05-24 at 1 02 12 pm](https://cloud.githubusercontent.com/assets/1022172/15512818/c5c18742-21af-11e6-8786-7fd097306b03.png)

**Comment by alloy** [comment]
Also need to report that artist to @mzikherman for having an incorrect artist image.

**Comment by alloy** [comment]
Fixed by #109.
