### ISSUE TITLE
[metaphysics] Missing shows data

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#11]
- [x] Number of artworks by artist X in a show
- [x] ausstellungsdauer, is the same format used across clients? If so, implement in metaphysics
- [x] formatted status string (i.e. Closing in 2 days; Opening Today)
- [ ] ~~shows filtered by status - call should take an array parameter for desired statuses (i.e. "running" & "upcoming")~~

**Comment by alloy** [comment]
I’m thinking that we don’t need to be able to pass an array of statuses for partner shows at all. We can just show the same component twice underneath each other, once for current shows and once for upcoming shows. Makes sense?

**Comment by sarahscott** [comment]
Ah yes it does. So we would sort them by date on our end, or potentially not need to if metaphysics returns them in order?

**Comment by alloy** [comment]
Yup, indeed.

**Comment by orta** [comment]
> ausstellungsdauer, is the same format used across clients? If so, implement in metaphysics

Aye, at least every implementation I've built is the same 👍

**Comment by alloy** [comment]
https://github.com/artsy/metaphysics/pull/226

**Comment by alloy** [comment]
![screen shot 2016-05-05 at 18 35 09](https://cloud.githubusercontent.com/assets/2320/15049853/d9ae1716-12f0-11e6-889e-45b50c294ff7.png)

**Comment by sarahscott** [comment]
Closing this 🎉
