### ISSUE TITLE
Re-create Semaphore integration

### ISSUE THREAD

**Issue by orta** [artsy/emission#116]
Since this repo went OSS, CI build results should ideally be public. The only way to do that is to [re-create the project](https://twitter.com/semaphoreci/status/735498351383314434) - I don't want to do this personally, as this is the first time I've started using Semaphor and I have no idea how things are set up.

**Comment by orta** [comment]
doh, too many JS repos ;)

**Comment by alloy** [comment]
Hah, what repo was this really about?

**Comment by orta** [comment]
metaphysics - https://github.com/artsy/metaphysics/issues/283 - CI was private as the repo was initially private https://github.com/artsy/metaphysics/issues/2
