### ISSUE TITLE
[RFC] Add react-native-svg

### ISSUE THREAD

**Issue by l2succes** [artsy/emission#1273]
### New Dependency

Name: react-native-svg
URL: https://github.com/react-native-community/react-native-svg

### Focus

Enables us to render scalable icons and dynamic change styling size based on current state on our map view and anywhere in the app. In the case of local discovery we have about 4 different type of icons with 3 states each. Moreover, all our icons in palette are already SVGs (https://github.com/artsy/palette/tree/master/src/svgs) so this library would allow us to use them in emission as well and further our goal of using palette as the source of truth for our style system.

### Check List

- [x] Have read over the source code, and we can maintain it
- [x] Has had a release in the last year, or looks done and stable

### Alternatives

- Using PNGs
 We already tried using PNGs instead and pins would look pixelated at higher zoom levels when changing the scale.

**Comment by alloy** [comment]
> We already tried using PNGs instead and pins would look pixelated at higher zoom levels when changing the scale.

I’m not sure I understand this correctly. Is this another issue than the one solved by having various versions of an icon for different device screen scales (or asset bundles)?

**Comment by zephraph** [comment]
Last time I talked to @orta about this he seemed fairly strongly against it. A potential alternative here is to convert SVGs over to PNGs via a snapshotting tool. I've actually done this exact thing in the performance-monitor repository. I use the library [repng](https://www.npmjs.com/package/repng) to [generate a snapshot](https://www.npmjs.com/package/repng) of a react component. It's a solution I had to use for emails because they don't support SVGs.

**Comment by ashfurrow** [comment]
The goal of including SVGs (directly from Zeplin) is definitely a good idea; having one asset that's scalable to any screen is a big win over PNGs. I'd be okay with including an SVG-to-PNG converter in a build process or something, but if this dependency works and it meets our criteria, then it sounds fine to me.

**Comment by l2succes** [comment]
Yes, I've had this discussion with @orta as well in the past but this use case is slightly different. We need to gradually scale the size our pin icon (max: 1.5x - min: 0.5x) as the user zooms in and out of the map. 

I took a video to illustrate what needs to happen.
<img src="https://user-images.githubusercontent.com/296775/51866186-4d9e8d80-2316-11e9-9cc2-36ad1c589e89.gif" width="320" />

**Comment by damassi** [comment]
My gut instinct is that `react-native` web is a pretty heavy-handed dependency for svg needs. Can't we just automate this behind a script?

**Comment by damassi** [comment]
Seems like a great addition barring any gotchas.

**Comment by l2succes** [comment]
@damassi it's my mistake with initially naming the RFC wrong when I first opened it, this has no dependency or anything to do with `react-native-web`.

**Comment by damassi** [comment]
Ah yeah, i just saw that and updated :)

**Comment by orta** [comment]
IMO, this doesn't pull its weight - shipping an entire SVG renderer for a single icon? We should just ship a really big icon and let it get resized correctly by the OS.

**Comment by ashfurrow** [comment]
@orta cool, I like the updated comment 👍 

I wanted to add that SVG's are already a part of our web stack, and adding support for SVG's in Emission would help share more expertise across web and iOS codebases.

**Comment by l2succes** [comment]
Thanks for thorough evaluation everyone and reconsidering @orta 🙏🏾 

Based on the feedback, we'll proceed. We actually have about a dozen SVGs for Local Discovery we'll be using this library for, including some of the ones in this screenshots below so it isn't just for one icon to be clear.

![screen shot 2019-01-29 at 3 25 48 pm](https://user-images.githubusercontent.com/296775/51938091-36c16f00-23da-11e9-9dd1-e0500ad17dca.png)

**Comment by zephraph** [comment]
Well, this'll make integrating palette icons easy breezy. Go team! 🎉
