### ISSUE TITLE
[Eigen] Automatically inset scrollviews when opened from search

### ISSUE THREAD

**Issue by alloy** [artsy/emission#129]
E.g. the bottom part of the view is behind the tab bar. This might also apply to the header.

![simulator screen shot 28 may 2016 00 48 48](https://cloud.githubusercontent.com/assets/2320/15622892/f9b2cfc8-246d-11e6-95cd-f9ff1e240e70.png)

**Comment by alloy** [comment]
This happens when coming in from a search result, not when tapping an artist elsewhere in the app.

**Comment by sarahscott** [comment]
This also messes up the header's top margin:

![image_0_1024](https://cloud.githubusercontent.com/assets/2712962/15636307/52086cb8-25af-11e6-8684-90678c6f8197.jpg)

**Comment by alloy** [comment]
This appears to be a general problem in Eigen, deferring for now and moving to Eigen: https://github.com/artsy/eigen/issues/1571
