### ISSUE TITLE
[Image] Get images sized according to screen DPI

### ISSUE THREAD

**Issue by alloy** [artsy/emission#13]
E.g. if we want to display an image at `200x100`, we should make GraphQL queries like so:

Screen scale:
1. `200x100`
2. `400x200`
3. `600x300`

For those images where we dynamically size based on the aspect ratio (e.g. masonry grid) we only specify 1 dimension (e.g. width) that’s specified according to screen scale and let metaphysics figure out the resize arguments based on the image’s aspect ratio.

**Comment by alloy** [comment]
https://facebook.github.io/relay/docs/api-reference-relay-container.html#preparevariables

**Comment by alloy** [comment]
The problem we’re facing with this is that we won’t know the view dimensions until _after_ a layout pass has been performed. This means that we’d have to:

1. Fetch initial metadata such as aspect ratio and all other Relay data for the current view.
2. Do a layout pass and start rending views.
3. Trigger additional Relay data fetches now that we know the size at which to display the view.

In a situation where there can be many image views, these additional fetches can add up, so this isn’t really an option. We also don’t want to hardcode all sizes for all devices, it needs to be dynamic.

As such, I think that we would need to generate the image variant URL on the client after all, which means that:

* we need metaphysics to return the template URL, we can do that during the initial fetch
* we need code to generate the template URL, which metaphysics already has, so maybe that can be extracted?

/cc @dzucconi

**Comment by orta** [comment]
> The problem we’re facing with this is that we won’t know the view dimensions until after a layout pass has been performed. This means that we’d have to:

Only on the current view, you could ask `UIScreen mainScreen`?

**Comment by alloy** [comment]
> Only on the current view

Do you mean, “for the time being” ? Because in the long-run, I’d really rather not rely on using the device screen in calculations in components.

**Comment by orta** [comment]
I did, aye

**Comment by orta** [comment]
I don't think you can pull it out of anywhere else other than those globals like `UIWindow` or `UIScreen`, which if you want this separated from the current view you're a bit stuck. An option is to have those pre-defined a global state when the app launches?

**Comment by orta** [comment]
Don't think I've ever heard of the scale changing on a UIView, but then on my Mac it is always shifting between retina/not retina as I have two screens

**Comment by alloy** [comment]
Not sure if we’re on the same page here, buddy, I’m not trying to deal with screen scale changing on a single device.

**Comment by orta** [comment]
You never know what apple can come up with at WWDC ;)

**Comment by alloy** [comment]
Ok, after reading the source for this it actually seems to be really simple. What I understand is:

* We use CloudFront to CDN host our images.
* CloudFront provides an image resizing API for images it hosts.

Thus, what we should do is:

1. During the Relay query we ask for:
    * the URL of the `large` version
    * the aspect ration of the image
2. Based on the aspect ratio we let our image view calculate the dimensions during the React shadow dom layout phase.
3. Once the image view has performed its layout, we take those measurements and generate a URL for it by using the CloudFront API.

**Comment by alloy** [comment]
#54 makes this work for images that are displayed according to their aspect ratio, but not yet for those that are cropped.

**Comment by alloy** [comment]
For cropped images, what needs to be done is, always get the regular ‘large’ URL of the image, then in the imageview component, if given width/height as style props (i.e. the user of the component wants a fixed size / crop), generate a URL like [this](https://github.com/artsy/emission/pull/54/files#diff-da61f6f33156049db872499f194f6f79R24), except one that crops.

[Here’s](https://metaphysics-production.artsy.net/?query=%7B%0A%20%20artist(id%3A%20%22monika-grzymala%22)%20%7B%0A%09%09artworks(size%3A%201)%20%7B%0A%20%20%20%20%20%20image%20%7B%0A%20%20%20%20%20%20%20%20url(version%3A%20%22large%22)%0A%20%20%20%20%20%20%20%20cropped(width%3A%20100%2C%20height%3A%20100)%20%7B%0A%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) an example where you can see that cropped URL basically just uses the large version in its request for a cropped version:

```json
          "image": {
            "url": "https://d32dm0rphc51dk.cloudfront.net/rHV84MOF6XApp7tAMwTT2A/large.jpg",
            "cropped": {
              "url": "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fill&width=100&height=100&quality=95&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FrHV84MOF6XApp7tAMwTT2A%2Flarge.jpg"
            }
          }
```

**Comment by alloy** [comment]
Oh, and then multiply the explicit styled width and height by the pixel ratio of the screen: https://github.com/artsy/emission/pull/54/files#diff-da61f6f33156049db872499f194f6f79R33
