### ISSUE TITLE
[Navigation Bar] Buttons should hide when scrolling.

### ISSUE THREAD

**Issue by alloy** [artsy/emission#132]
Basically, Eigen’s [scroll chief](https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/Util/ARScrollNavigationChief.h) needs to hook into the scrollview that’s put on screen from RN so that it can hide the buttons when needed.

**Comment by orta** [comment]
Perhaps we could find a way to be declarative about this?

**Comment by alloy** [comment]
What about making this part of the 'menu aware' protocol? So if the VC implements that, the scroll view gets the chief as delegate?

**Comment by orta** [comment]
Yep, definitely a good idea!

**Comment by alloy** [comment]
Ace. I’m not yet sure about how we should best intercept, though. Should we have a `UIScrollViewDelegate` that forwards to multiple delegates?

**Comment by orta** [comment]
So sometimes we need to do work on scroll ( like in your case, loading extra artworks ) and sometimes we don't need it at all. Could we do something with `AIMultiDelegate` which is already in there to allow both self & chief to get the callbacks?

**Comment by alloy** [comment]
Aye, that sounds good 👍
