### ISSUE TITLE
Think of way to more declaratively add analytics to components.

### ISSUE THREAD

**Issue by alloy** [artsy/emission#137]
In Eigen we have [a source file](https://github.com/artsy/eigen/blob/master/Artsy/App/ARAppDelegate+Analytics.m) that lives outside of the tracked views and declaratively describes all of the events that need to be tracked.

Some quick googling for existing React solutions:
- https://github.com/yahoo/react-i13n
- https://github.com/nfl/react-metrics

**Comment by sarahscott** [comment]
@mennenia can I close this?

**Comment by mennenia** [comment]
probably yes, there are more recent tickets now :) thanks @sarahscott!
