### ISSUE TITLE
[Shows] Crash when no meta_image is available

### ISSUE THREAD

**Issue by alloy** [artsy/emission#139]
This show has none https://www.artsy.net/show/serpentine-galleries-alex-katz. Looking at the shows for Alex Katz on Force doesn’t seem to reveal this show at all: https://www.artsy.net/artist/alex-katz/shows.

So either Force is not showing shows where the `meta_image` is missing or they are filtering out this show based on another flag that I have not been able to figure out, based on [the data in metaphysics](https://metaphysics-production.artsy.net/?query=%7B%0A%09partner_show(id%3A%20%22serpentine-galleries-alex-katz%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20description%0A%20%20%20%20is_fair_booth%0A%20%20%20%20status%0A%20%20%20%20images(size%3A%201)%20%7B%0A%20%20%20%20%20%20url%0A%20%20%20%20%7D%0A%20%20%20%20meta_image%20%7B%0A%20%20%20%20%20%20href%0A%20%20%20%20%7D%0A%20%20%20%20cover_image%20%7B%0A%20%20%20%20%20%20href%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) at least.

We shouldn’t even crash, but I would like to know if this is simply a problem with the show metadata that needs to be fixed or that we need to be doing something differently.

**Comment by dzucconi** [comment]
It looks likely that if there isn't a cover image the show is not displayed. I think maybe @1aurabrown could tell you for certain.
