### ISSUE TITLE
[iPad] Past Shows issues.

### ISSUE THREAD

**Issue by alloy** [artsy/emission#155]
## When loading shows in portrait orientation and then rotating to landscape orientation the grid changes to 4 columns.

It should always be 3 columns.

![simulator screen shot 02 jun 2016 15 22 45](https://cloud.githubusercontent.com/assets/2320/15746318/593294bc-28d6-11e6-833a-7134f0fde03a.png)

## When loading shows in landscape orientation and then rotating to portrait orientation the columns don’t decrease in size and changes to 2 columns.

![simulator screen shot 02 jun 2016 15 36 58](https://cloud.githubusercontent.com/assets/2320/15746682/db942e24-28d7-11e6-9b98-d0d7e24aec0d.png)

**Comment by mennenia** [comment]
Update here. @briansw stated that ideally we do have four columns in landscape on iPad.

Also, the second issue seems to be the same as the relatedArtist issue #152, so if that is fixed this can be fixed probably with the same approach.
