### ISSUE TITLE
Navigating to a new artist displays Works component but About tab is selected

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#157]
![simulator screen shot jun 2 2016 10 53 18 am](https://cloud.githubusercontent.com/assets/2712962/15755184/878e600a-28b0-11e6-9d23-3ec69963f620.png)

**Comment by mennenia** [comment]
@sarahscott - I can't reproduce this on the current version of master..

**Comment by alloy** [comment]
I’m guessing this might be due to you not rebuilding the Xcode project, but only reloading the JS.

**Comment by sarahscott** [comment]
Yeah I can't repro it on the fresh build; closing now!
