### ISSUE TITLE
[iPad] Get rid of window checking.

### ISSUE THREAD

**Issue by alloy** [artsy/emission#160]
It’s bad to assume that a view is going to span e.g. the full width of a window, so we really shouldn’t rely on the window dimensions.

We probably need to do an initial render pass with an **empty** container that has a `onLayout` callback to get the laid out component’s size and _then_ do a second render pass that actually adds the children.

We can’t really be the first ones to deal with that, so we should check if this pattern has already been abstracted and/or what others are doing.

**Comment by orta** [comment]
and just to make sure it's obvious, we can't trust that windows will ever be the same size consistently, with rotation and iPad split views 👍

**Comment by alloy** [comment]
Never trust windows!!

![](http://alatown.com.s30748.gridserver.com/wp-content/gallery/windowless-homes/nana-han-japanese-house-by-shu-588x478.jpg)

**Comment by sarahscott** [comment]
Closing in favor of #240
