### ISSUE TITLE
Port to TypeScript

### ISSUE THREAD

**Issue by alloy** [artsy/emission#18]
Requires:
- [ ] Type definitions for latest React
- [ ] Type definitions for latest React Native
- [ ] Setting up compiler
- [ ] Ensuring VS Code is properly configured for our project
- [ ] Add type annotations to our existing code

**Comment by orta** [comment]
Want to keep this issue around @alloy ?

**Comment by alloy** [comment]
👍

**Comment by alloy** [comment]
Now that we know that our Relay needs can work, let’s make the move to TypeScript while the codebase is still manageable!

**Comment by orta** [comment]
Done some deeper looking into this, most of this looks feasible, but I think we'll need to do a trivial example app first to prove the concept. 

The transiplaition/[transformer](https://github.com/facebook/react-native/commit/dd9b3e13a95013b8e399602fbb0bdaee14fbc7f5) flow is a bit more complex as we can't rely on ts-babel-node for dev like we do in relational theory.

**Comment by orta** [comment]
Started this, https://github.com/orta/systems-theory

**Comment by alloy** [comment]
@l2succes @sarahscott Also see #422.

**Comment by orta** [comment]
Done
