### ISSUE TITLE
[RFC] Add INTUAnimationEngine

### ISSUE THREAD

**Issue by ds300** [artsy/emission#1815]
## Proposal

Add the `INTUAnimationEngine` library as a dependency to emission.

`INTUAnimationEngine` is a tiny objective-c library for animating arbitrary properties. It supports springs, easing functions, and makes interpolation easy.

https://github.com/intuit/AnimationEngine

## Reasoning

I'm using it in this PR #1812 to animate the `contentOffset` and `zoomScale` properties of a scroll view in order to trigger scroll events for every stage of an automated zoom transition. Unfortunately the built-in `zoomToRect` method doesn't do that. When I googled for a solution to that problem, `INTUAnimationEngine` was mentioned in a few places.

## Additional Context

As a library it seems small and stable. Its API is clear and has everything you'd expect. It has 1000 stars on github and basically no issues ever. It seems well-written, with plenty of comments, and I think even with my fairly rudimentary obj-c knowledge I would be confident maintaining it, should the need arise.

## How is this RFC resolved?

I will post a link to this in the front-end-ios channel. If nobody has questions or concerns then we will resolve. Otherwise we can discuss alternative solutions and try to find a different way forward.

**Comment by alloy** [comment]
It would be good to check if Eigen’s Podfile.lock has any dependencies in its tree that are similar.

Otherwise, after quickly skimming the source, this looks good to me. No deps of its own, MIT & BSD licenses, seemingly stable for years, reputable developers. 👍

**Comment by ds300** [comment]
> It would be good to check if Eigen’s Podfile.lock has any dependencies in its tree that are similar.

Couldn't see anything in eigen

**Comment by alloy** [comment]
Let's see what @ashfurrow says, but this seems fine to me 👍

**Comment by ashfurrow** [comment]
Looks good to me 👍 The library itself seems small, and is built on top of `CADisplayLink` (a well-defined class from Apple's libraries). Should be totally safe.

**Comment by ds300** [comment]
Great! Let's consider this RFC resolved then :+1:
