### ISSUE TITLE
[metaphysics] Check if we have required personalised home rails data

### ISSUE THREAD

**Issue by alloy** [artsy/emission#191]
- [x] Works by Galleries You Follow
- [x] Personalised Genes
- [x] Is the artwork auction data (current bid amount and bids count) available?

**Comment by alloy** [comment]
Artwork auction data example:

```graphql
{
  artwork(id: "robert-indiana-decade-no-6") {
    is_in_auction
    sale_artwork {
      sale {
        id
      }
      is_bid_on
      current_bid {
        display
        amount
        cents
      }
    }
  }
}
```

```json
{
  "data": {
    "artwork": {
      "is_in_auction": true,
      "sale_artwork": {
        "sale": {
          "id": "heather-james-fine-art-benefit-auction-2016"
        },
        "is_bid_on": true,
        "current_bid": {
          "display": "$1,600",
          "amount": "$1,600",
          "cents": 160000
        }
      }
    }
  }
}
```

**Comment by mzikherman** [comment]
`display` is just a formatted string from the server.

`amount` is a DSL to a bunch of number formatting that you can apply to the raw 'cents'.

https://github.com/artsy/metaphysics/blob/0030b46633766101ad85c5f0c3496ecd14101122/schema/fields/money.js#L56-L64

The options to amount (https://github.com/artsy/metaphysics/blob/0030b46633766101ad85c5f0c3496ecd14101122/schema/fields/money.js#L9-L41) , which do actually have descriptions.

example use:

```
{
  artwork(id: "robert-indiana-decade-no-6") {
    is_in_auction
    sale_artwork {
      sale {
        id
      }
      is_bid_on
      current_bid {
        display
        amount(precision: 1)
        cents
      }
    }
  }
}
```

```
{
  "data": {
    "artwork": {
      "is_in_auction": true,
      "sale_artwork": {
        "sale": {
          "id": "heather-james-fine-art-benefit-auction-2016"
        },
        "is_bid_on": true,
        "current_bid": {
          "display": "$1,700",
          "amount": "$1,700.0",
          "cents": 170000
        }
      }
    }
  }
}
```

I fully agree the more componentization/libraries/shared code we start to use, the more digging required! This could be better explained I think.
