### ISSUE TITLE
Dumping the schema requires `babel-cli`

### ISSUE THREAD

**Issue by orta** [artsy/emission#214]
![screen shot 2016-07-19 at 1 29 39 pm](https://cloud.githubusercontent.com/assets/49038/16959829/dce1cb2c-4db4-11e6-81ad-5828382a6f9c.png)

Not really too sure if this should go in metaphysics, or just in here TBH. Figured it'd be better to bring it up in here first.

**Comment by alloy** [comment]
Yeah this is an issue I’ve been wanting to dive into, but when I wanted to it went away for me :/

The `babel-cli` package is actually being used by metaphysics, so ¯\_(ツ)_/¯
