### ISSUE TITLE
[Home] [Artist Rail] Add follow action

### ISSUE THREAD

**Issue by mennenia** [artsy/emission#218]
Make the follow button work (and check any issues/conflicts with Artist view, as there are comments in there re:this).

**Comment by mennenia** [comment]
@alloy this was the outstanding bit of functionality needed. 

I had a stash for this that I'll [push up](https://github.com/artsy/emission/tree/mc-followbutton), which essentially copied off the follow button in the artist header.

There were however problems when you followed an artist, then followed a second artist in the rail, and then unfollowed one (I believe). Try following and unfollowing a few, and the problem should happen. 

I didn't get a chance to finish debugging this. Here's what I got:

![simulator screen shot 29 jul 2016- 13 53 09](https://cloud.githubusercontent.com/assets/373860/17890336/334d14a6-692d-11e6-99dc-42c34c76ec0e.png)

**Comment by sarahscott** [comment]
FWIW I've seen this happen in the [Artist VC](https://github.com/artsy/emission/blob/master/lib/components/artist/header.js#L72) in the simulator but not when integrated into the rest of eigen.

**Comment by alloy** [comment]
Ok, my bad for not spotting this in the error details immediately. What you are seeing is [a simulated error](https://github.com/artsy/emission/blob/2bf112f24bf59f5e3956e5e702e526f40bb9adc8/Example/Emission/AppDelegate.m#L210-L211), which is there to test that an error from the API layer is handled as expected; which in [dev mode is to see the red box error but only log in production](https://github.com/artsy/emission/commit/40ffd66e77bd5ea3ea8f9cc6e202e060bb9b3aba#diff-71c391b194a95d165bb0d7ae3ac41bb1R31).

**Comment by alloy** [comment]
I’ll work on this right now!

**Comment by mennenia** [comment]
ohhhhhh. but it still errors for some reason, right?

**Comment by alloy** [comment]
It’s just completely random https://github.com/artsy/emission/blob/2bf112f24bf59f5e3956e5e702e526f40bb9adc8/Example/Emission/AppDelegate.m#L207 😄

**Comment by mennenia** [comment]
WHAT

WHAT

SO MUCH GRIEF ;_;

I tried to fix this for aageesss (well, only two days or so lol). 

Anyway, yay for finding that! 🎉

**Comment by alloy** [comment]
Sowwwwwy…

**Comment by alloy** [comment]
Closed by #296.
