### ISSUE TITLE
[Home/Artworks] Missing ‘VIEW ALL’ link in header

### ISSUE THREAD

**Issue by alloy** [artsy/emission#246]
## Design

<img width="375" alt="screen shot 2016-08-24 at 12 15 07" src="https://cloud.githubusercontent.com/assets/2320/17927169/b04a6978-69f4-11e6-9e76-5d3bd555b215.png">

## Actual

![simulator screen shot 24 aug 2016 12 14 20](https://cloud.githubusercontent.com/assets/2320/17927179/bb00d3ac-69f4-11e6-99e5-0f61ec05e1f4.png)

**Comment by alloy** [comment]
I just noticed that it _is_ present in the ‘works by artists you follow’ rail but _only_ there, so not sure what’s going on here.

![simulator screen shot 24 aug 2016 12 25 15](https://cloud.githubusercontent.com/assets/2320/17927420/dec63b64-69f5-11e6-83b5-92936291e592.png)

**Comment by sarahscott** [comment]
It's showing up for me on genes and other rails with additional content:

![simulator screen shot aug 26 2016 2 08 02 pm](https://cloud.githubusercontent.com/assets/2712962/18004810/8d8734ae-6b96-11e6-94e3-2325f428be39.png)

@alloy is it still not showing up?

**Comment by alloy** [comment]
This is a non-issue 👍
