### ISSUE TITLE
[Home] Heading font weight

### ISSUE THREAD

**Issue by alloy** [artsy/emission#248]
I think the font weight needs to be increased to be in-line with the design, but this might also just be a photoshop vs iOS difference. @katarinabatina can you chime in?

## Design

<img width="374" alt="screen shot 2016-08-24 at 12 28 28" src="https://cloud.githubusercontent.com/assets/2320/17927544/7c11080e-69f6-11e6-9eb4-b4ae12471de5.png">

## iOS

<img width="377" alt="screen shot 2016-08-24 at 12 30 17" src="https://cloud.githubusercontent.com/assets/2320/17927561/8dc8a228-69f6-11e6-9ca6-c0347e14eb6d.png">

**Comment by katarinabatina** [comment]
Yea sketch renders thinks a bit "heavier" than reality. No need to change the font.

Sent with thumbs,
Katarina Batina 
Product Designer
Artsy.net

**Comment by alloy** [comment]
Thanks 👍
