### ISSUE TITLE
[React Native] Look into running debugger in actual iOS env

### ISSUE THREAD

**Issue by alloy** [artsy/emission#250]
Currently when debugging the JS will be run inside Chrome, which means that it does not 100% reflect the actual env that the code will eventually run in.

There’s [talk about running inside a Node.js process](https://github.com/facebook/react-native/issues/8641) instead, however, that still doesn’t definitively solve the issue.

Reading about how MS has [added iOS debugging support to VS Code](https://blogs.msdn.microsoft.com/webdiagnostics/2016/08/22/introducing-ios-web-debugging-for-vs-code-on-windows-and-mac/), I came across a lib that might make it more feasible to run on the real iOS env: https://github.com/google/ios-webkit-debug-proxy

**Comment by orta** [comment]
This is fascinating read

**Comment by alloy** [comment]
Going to close this for now.
