### ISSUE TITLE
[Home][ArtistRail] Follow button disappears on iPad

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#257]
![simulator screen shot aug 26 2016 1 46 18 pm](https://cloud.githubusercontent.com/assets/2712962/18004338/88d2b74c-6b93-11e6-97f8-c5c6c255a6ec.png)

**Comment by alloy** [comment]
Can you try to check the ‘DOM’ with the ‘Show Inspector’ option in the debug menu (shake) ?
