### ISSUE TITLE
[Artist Rail] Header text should be over two lines on iPhone

### ISSUE THREAD

**Issue by mennenia** [artsy/emission#267]
Current:

![simulator screen shot 1 sep 2016 13 15 24](https://cloud.githubusercontent.com/assets/373860/18167018/43cc30d0-7046-11e6-9d58-9e8ef8358bf1.png)

[Spec](https://github.com/artsy/eigen/issues/1440) :

<img width="245" alt="screen shot 2016-09-01 at 13 17 02" src="https://cloud.githubusercontent.com/assets/373860/18167060/6f51e1be-7046-11e6-9492-c0a592c60e1b.png">

**Comment by mennenia** [comment]
@katarinabatina or is it ok to stretch out if there's space? This may be a non issue lol.

**Comment by katarinabatina** [comment]
Yup that's fine! 

Sent with thumbs,
Katarina Batina 
Product Designer
Artsy.net
