### ISSUE TITLE
[Home] Include more generic gene rails

### ISSUE THREAD

**Issue by alloy** [artsy/emission#274]
See https://artsy.wake.io/1085

**Comment by sarahscott** [comment]
Should I take this on and perhaps talk to the web team about how it will affect their home view?

**Comment by alloy** [comment]
There’s [this](https://github.com/artsy/metaphysics/blob/9b8a1b35dcaa66e52b5a8e5e325c98ac9d8e8114/schema/home/home_page_artwork_modules.js#L29-L33) `max_rails` argument, except it’s not correct for our needs. What we need is an extra arg to “always include all generic genes”, as per the design spec.

<img width="738" alt="screen shot 2016-09-02 at 22 25 54" src="https://cloud.githubusercontent.com/assets/2320/18217280/42a79b92-715c-11e6-9fbe-f8144c3ec1e1.png">

You should be able to just add that arg and default to `false`, which should make it compatible with Force.
