### ISSUE TITLE
[Home] Improve margins between rails

### ISSUE THREAD

**Issue by mennenia** [artsy/emission#277]
Margins differ between collapsed and expanded artwork rails. 

![simulator screen shot 1 sep 2016 15 16 11](https://cloud.githubusercontent.com/assets/373860/18202682/ab6bea0a-7109-11e6-9e3c-98eb5621feef.png) 

![simulator screen shot 1 sep 2016 15 15 51](https://cloud.githubusercontent.com/assets/373860/18202683/ab6dd6bc-7109-11e6-90b2-c0337a975a22.png)

**Comment by alloy** [comment]
Fixed!
