### ISSUE TITLE
auction artworks showing contact for price

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#282]
currently showing contact for price in artwork metadata, should show bid now. screenshot coming

**Comment by alloy** [comment]
bump

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/18729652/9a49005c-8020-11e6-9973-77deff792903.png)

**Comment by alloy** [comment]
Just a simple ‘bid now’ link.

**Comment by alloy** [comment]
Do you want that paddle icon next to the ‘Bid now’ label? If so, can you give me 1x, 2x, and 3x versions that fit nicely next to these labels (2x scale rendering):

![simulator screen shot 28 sep 2016 18 11 21](https://cloud.githubusercontent.com/assets/2320/18921991/3a9a585e-85a7-11e6-9e63-827087abfdc9.png)

**Comment by katarinabatina** [comment]
file to three sizes https://cl.ly/3m0m1i26013r

there should be 4 px of space between the paddle and the start of Bid Now
![image](https://cloud.githubusercontent.com/assets/6482926/18924495/6abff364-857e-11e6-8803-3b6b410d31e5.png)

**Comment by alloy** [comment]
This has been done 👍
