### ISSUE TITLE
[Home/Artist] Artist with long name can break layout.

### ISSUE THREAD

**Issue by alloy** [artsy/emission#303]
![simulator screen shot 21 sep 2016 22 29 37](https://cloud.githubusercontent.com/assets/2320/18728469/83a86518-804d-11e6-9805-2479c5eaa434.png)

**Comment by mennenia** [comment]
Siiii. It's supposed to truncate. Wonder why it doesn't. Will check and fix!

**Comment by alloy** [comment]
This card came in after replacing.

**Comment by alloy** [comment]
Might be related to https://github.com/artsy/emission/issues/200
