### ISSUE TITLE
Works by artists you follow shows up even though I didn't follow any artists

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#308]
go through onboarding, don't follow any artists, get works by artists you follow with endless spinner
![image](https://cloud.githubusercontent.com/assets/6482926/18839488/2a9468a2-83d9-11e6-8bba-bab65fcbe8ae.png)

**Comment by alloy** [comment]
Apparently it was decided that on Force this rail should _always_ be shown, although it doesn’t end-up actually showing. Starting discussion here https://github.com/artsy/metaphysics/pull/289

**Comment by alloy** [comment]
Should be fixed with https://github.com/artsy/metaphysics/pull/443
