### ISSUE TITLE
tap artist card, get unable to load

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#312]
I am unable to reproduce this consistently but I've seen it a fair amount of times. Tapping the please try to reload button several times does not successfully load the artist VC 

![image](https://cloud.githubusercontent.com/assets/6482926/18839794/45dc9674-83da-11e6-88c3-171c2ee16a58.png)

**Comment by alloy** [comment]
This is on production.

**Comment by alloy** [comment]
I think what’s happening is that some error occurs on metaphysics and the presence of those errors in the response is making Relay consider the returned data unreliable.

I just fixed one such issue https://github.com/artsy/metaphysics/pull/415.

For others I started making sure that we surface those errors as the occur on metaphysics https://github.com/artsy/metaphysics/pull/416.

**Comment by alloy** [comment]
@katarinabatina @mennenia @sarahscott When/if you run into this issue, please post what artist you were trying to view.
