### ISSUE TITLE
[Home] Recommended works should be in first position on home feed

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#314]
for reference, here's the feed logic we discussed when we we're discussing how we would be different from /force cc: @alloy 

![image](https://cloud.githubusercontent.com/assets/6482926/18849365/a71f2d22-8400-11e6-8484-dcb137cb05e8.png)

**Comment by sarahscott** [comment]
Should this be done in metaphysics or client-side?

**Comment by alloy** [comment]
Fixed by #374
