### ISSUE TITLE
[Relay] Persist cache for fast load on next app launch.

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#320]
after not using the app for a few hours I open it, get the spinner on the home screen and then get the unable to load screen. After tapping the refresh button I get new content. Can we just save/store where the user was last?

**Comment by alloy** [comment]
Might be related to https://github.com/artsy/emission/issues/317

**Comment by alloy** [comment]
Interesting, it appears that there does exist internal hooks for Relay to maybe make offline caching work https://github.com/facebook/relay/issues/1030, I could take a stab at writing a native component for that.

**Comment by alloy** [comment]
Going to punt on this for now.

**Comment by orta** [comment]
Aye, probably worth waiting till Relay 2.0
