### ISSUE TITLE
Fix flow, and put it on CI

### ISSUE THREAD

**Issue by orta** [artsy/emission#322]
Running `npm run flow` gives us 137 errors, we should get this on CI once it's down to zero.

**Comment by alloy** [comment]
Ooohhhh, I thought we were running those.

**Comment by orta** [comment]
Nope, I just turned it back on on my editor and it found a bunch of my gene bugs

**Comment by alloy** [comment]
> I just turned it back on on my editor

Can you elaborate on this? Is it not enabled currently or are they surfaced differently?

**Comment by orta** [comment]
Sure, back when we were trying to figure out what was going wrong with emission + react native - here https://github.com/artsy/emission/pull/299 - I uninstalled all my extensions and added them one by one, I never added back Flow to VS Code. 

I re-installed it when I was suspicious of the jump to symbol when exploring the codebase today.

**Comment by orta** [comment]
This happened, so then did TS
