### ISSUE TITLE
If network connection goes down during loading, it is possible to get endless spinners

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#333]
To repro:

Open Home and wait until rail titles load, then cut network connectivity.

This will result in individual rails failing to load even when network connectivity has been restored and the user pulls-to-refresh:

![simulator screen shot oct 6 2016 5 54 20 pm](https://cloud.githubusercontent.com/assets/2712962/19159647/89dd562c-8bed-11e6-9efb-34d26070ee5b.png)

**Comment by mennenia** [comment]
Current behaviour is that now, these rails will be set to `null`. Closing this for now, and opening a new ticket for improved behaviour (#366).
