### ISSUE TITLE
[Home] Don’t show empty ‘Artists to Follow: Popular’ rail.

### ISSUE THREAD

**Issue by alloy** [artsy/emission#339]
It’s possible to follow all artists in this rail after which an empty rail is shown. Ideally we always show artists, but alternatively we’d have to not show the rail at all.

![asset png-3](https://cloud.githubusercontent.com/assets/2320/19305793/e59d433a-9072-11e6-809b-5e6234d96df1.jpeg)

**Comment by alloy** [comment]
@katarinabatina Probably not a showstopper, but not sure if p0 or p1. It’s unlikely people would run into this fast, but it’s ugly when it happens.

**Comment by alloy** [comment]
See https://github.com/artsy/gravity/pull/10316/files#r82974321

**Comment by katarinabatina** [comment]
@alloy realistically, how could someone follow every artist?? How long would it take to get into this state?

**Comment by alloy** [comment]
Took me a minute. It’s not so much a matter of time, more a matter of it being unlikely (naive guess) that somebody would truly follow all of them. Having said that, it seems like a fix wouldn’t bee too hard, just needs to be done on Gravity.

**Comment by alloy** [comment]
See https://github.com/artsy/gravity/issues/10479

**Comment by katarinabatina** [comment]
@alloy sounds like we'll have the gravity fix in. In general I think we should continue to fall back into a looooong list of artists so that a user would never reasonably run out of artists to follow. Maybe after the 100 popular artists cache we just open it up to any artist or a larger subset of that list.

**Comment by alloy** [comment]
Still need to finish the Gravity change.

**Comment by alloy** [comment]
Fixed by https://github.com/artsy/gravity/pull/10480
