### ISSUE TITLE
[Shows] Vertically center show metadata

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#34]
This should be centered vertically with the thumbnail:

![simulator screen shot may 6 2016 1 54 52 pm](https://cloud.githubusercontent.com/assets/2712962/15081752/5642456c-1392-11e6-870b-54748c3374a0.png)

**Comment by mennenia** [comment]
No `alignCenterYWithView`? T_T

**Comment by alloy** [comment]
There’s `alignItems` or `alignSelf` that should do the trick! https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by alloy** [comment]
Ooooh, just found this http://blog.krawaller.se/posts/a-react-app-demonstrating-css3-flexbox/

**Comment by mennenia** [comment]
🎉

**Comment by sarahscott** [comment]
Flexbox is magic

**Comment by alloy** [comment]
Fixed by #36.
