### ISSUE TITLE
header area of gene view over stretched on ipad

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#355]
should look like the artist view, limiting the width of the follow button and tab system

![image](https://cloud.githubusercontent.com/assets/6482926/19411449/1cce7f04-92d0-11e6-9df3-994c6d0f76ad.png)

current
![image](https://cloud.githubusercontent.com/assets/6482926/19411450/275d576a-92d0-11e6-8541-ad8c81ea05f5.png)

**Comment by alloy** [comment]
Fixed by #362.
