### ISSUE TITLE
refine area adjustments 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#356]
button is oddly sized, too crammed 
current
![image](https://cloud.githubusercontent.com/assets/6482926/19411487/a274ae8a-92d0-11e6-81bb-7630035d48d6.png)

should be (taken from auction sale page vc)
![image](https://cloud.githubusercontent.com/assets/6482926/19411496/c70ccfb6-92d0-11e6-8105-068ba8950630.png)

separator area rules should not be shown by default, only when the view is scrolled (current)
![image](https://cloud.githubusercontent.com/assets/6482926/19411507/005ee8e4-92d1-11e6-877c-fc171fa2103a.png)

spec
![image](https://cloud.githubusercontent.com/assets/6482926/19411515/25b8080a-92d1-11e6-91a9-e2b7fa5bfe4f.png)

**Comment by orta** [comment]
All of those were fixed 👍
