### ISSUE TITLE
increase type size on gene title on ipad to 20px

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#357]
![image](https://cloud.githubusercontent.com/assets/6482926/19411595/c5746e00-92d2-11e6-9a60-9829b25aac5b.png)

**Comment by katarinabatina** [comment]
current:
![image](https://cloud.githubusercontent.com/assets/6482926/19411628/47637776-92d3-11e6-970e-2cefb87a41ba.png)


should be:
![image](https://cloud.githubusercontent.com/assets/6482926/19411630/4d035002-92d3-11e6-8c2b-da265034a106.png)

**Comment by alloy** [comment]
Fixed by #362.
