### ISSUE TITLE
Fix emission-in-eigen on iPad

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#365]
When I try to run emission in eigen on iPad, the app will build but immediately crash with this sort of error: https://github.com/soffes/SAMKeychain/issues/126

Will probably be fixed by something like this: http://stackoverflow.com/questions/24002836/dyld-library-not-loaded-rpath-libswift-stdlib-core-dylib/27109546#27109546

**Comment by orta** [comment]
This feels weird to me, Emissions's [Podspec does not mention SAMKeychain](https://github.com/artsy/emission/blob/master/Emission.podspec#L20-L30) and so it won't be added as a dependency in Eigen.

It should only be there inside the Emission app, is there any chance you are mixing the packager and the Emission example app?

**Comment by sarahscott** [comment]
Should have clarified- the error was on a different pod but this issue with SAMKeychain was one of the only results that came up when searching for this error.

**Comment by alloy** [comment]
This feels very much like a build artefact issue, try cleaning your eigen build.

**Comment by alloy** [comment]
Closing this for now, please re-open if it remains an issue.
