### ISSUE TITLE
gene view header area is clashing with back button

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#370]
on the left is our auction sale VC, on the right is current gene view

looks like the header area needs to increase in size to get the button to not clash with the fitered data

![image](https://cloud.githubusercontent.com/assets/6482926/19537580/86c33f20-961e-11e6-9f19-1300985bd2d7.png)

**Comment by orta** [comment]
This feels off, I've been working with the same setup as eigen, perhaps #368 may have made changes to this

<img width="456" alt="screen shot 2016-10-19 at 22 53 48" src="https://cloud.githubusercontent.com/assets/49038/19539019/eede5fa6-964e-11e6-9d3f-c1777fc415ee.png">

Will give it a run tomoroow
