### ISSUE TITLE
Auction results send users to old artist page

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#392]
tap auction results, get sent to old page. we should send users directly to the auction results MG view.

**Comment by alloy** [comment]
Btw, on iPad this gives you access to the full Force version of the artist page:

![simulator screen shot 15 nov 2016 21 51 08](https://cloud.githubusercontent.com/assets/2320/20333007/ae49bfc8-ab7d-11e6-8bf0-5949cb4f47e5.png)

**Comment by katarinabatina** [comment]
Ugh yikes. Would likely be a sizable work item to strip out the top half of the page for embedding in eigen yea?

**Comment by alloy** [comment]
I _think_ so, but I can check with people that know Force’s code better than I do.
