### ISSUE TITLE
Add testing to Emission

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#404]
See: https://github.com/artsy/emission/pull/403

**Comment by sarahscott** [comment]
Sub-issue: #407

**Comment by sarahscott** [comment]
Helpful readings: 
- [Jest for RN Tutorial](https://facebook.github.io/jest/docs/tutorial-react-native.html#content)
- [Testing React Native with the *new* Jest](https://blog.callstack.io/unit-testing-react-native-with-the-new-jest-i-snapshots-come-into-play-68ba19b1b9fe#.veszx7uwn)
- [React Native docs on different approaches to testing](https://facebook.github.io/react-native/docs/testing.html)

**Comment by alloy** [comment]
@sarahscott Can this be closed?

**Comment by sarahscott** [comment]
Yes
