### ISSUE TITLE
[Testing] Implement testing for RN containers

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#407]
As a start, we are going to implement snapshot and logic verification tests using Jest. Eventually, we would like to add some integration tests from eigen, but these will be part of a separate endeavor outlined [here](https://github.com/artsy/eigen/issues/2053). 

After we have a foundation of container tests, I'm hoping a pattern will emerge for more granular component tests.

**Comment by alloy** [comment]
@sarahscott Can this be closed?

**Comment by sarahscott** [comment]
Yes
