### ISSUE TITLE
Update RN version when appropriate to do so

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#408]
We are currently using a [custom fork](https://github.com/alloy/react-native/commits/0.34.1-with-scrollview-fix) of RN version 0.34.1 with an important bug fix. When this has been addressed in an RN release, we should update.

**Comment by orta** [comment]
I think we need to change the babel reference for Jest when we update RN too, think the pluging name changes

**Comment by orta** [comment]
This one is a blocker on #18 

Does look like the commit we want is inside the fb repo: https://github.com/facebook/react-native/commit/73fa7b42b1a1384d9661fca4ddffd85a10ad94dc 

I don't see a PR for it though: https://github.com/facebook/react-native/pulls?utf8=✓&q=is%3Apr%20user%3Aalloy%20author%3Aalloy%20

**Comment by orta** [comment]
The commit may be in the repo, but the actual code isn't in there

compare: [ours](https://github.com/facebook/react-native/commit/73fa7b42b1a1384d9661fca4ddffd85a10ad94dc#diff-973dcd0e3fbfcc5e35485bb6404a2fd2R139) [theirs](https://github.com/facebook/react-native/blob/master/React/Views/RCTScrollView.m#L142)

**Comment by alloy** [comment]
There's no PR because FB was testing it internally and in the end they deemed the fix not the best (something with modal views). However, I just learned about an experimental WindowedListView, maybe see if that fixes it all?

**Comment by alloy** [comment]
We did.
