### ISSUE TITLE
pod install asks for a password

### ISSUE THREAD

**Issue by hffmnn** [artsy/emission#418]
Hi there.

When stepping through your Installation guide I found the following blocker when executing step 5:
`cd Example && ARTSY_STAFF_MEMBER=true pod install` gives me:

```
Analyzing dependencies
Pre-downloading: `Artsy+Authentication` from `https://github.com/artsy/Artsy-Authentication.git`, commit `1b582675598c999726d9edacd3b8559e01cf7c48`
Pre-downloading: `Artsy+UIFonts` from `https://github.com/artsy/Artsy-UIFonts.git`, commit `6295cce382764bbca9f2b3e972f71eb2b4d32d57`
Username for 'https://github.com':
```

When giving it my credentials it fails with:
```
Cloning into '/var/folders/gq/kmmb81cj29v3w83_yzr2md980000gn/T/d20170104-36677-14nu3qf'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/artsy/Artsy-UIFonts.git/'
```

(Maybe) somehow related: Doing a `pod install` on eigen I get:
```
Analyzing dependencies
Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`
Downloading dependencies
Using AFNetworkActivityLogger (2.0.4)
Using AFNetworking (2.5.4)
Using AFOAuth1Client (0.4.0)
Using ALPValidator (0.0.3)
Using ARAnalytics (3.9.0)
Using ARCollectionViewMasonryLayout (2.1.2)
Using ARGenericTableViewController (1.0.2)
Using ARTiledImageView (1.2.0)
Using Adjust (4.5.0)
Using Aerodramus (0.1.0)
Using Analytics (3.0.7)
Using AppHub (0.5.1)
Installing Artsy+OSSUIFonts (2.0.2)
Using Artsy+UIColors (3.0.1)
Installing Artsy+UIFonts (1.1.1)
Username for 'https://github.com':...
```

Any ideas how to fix that?

**Comment by orta** [comment]
You're running with `ARTSY_STAFF_MEMBER=true` when you're not a staff member, so you don't have access to [our private repo](https://artsy.github.io/blog/2014/06/20/artsys-first-closed-source-pod/)

**Comment by orta** [comment]
oops, hit return too early,  It should work without that ENV var in your command

**Comment by orta** [comment]
Ah, this is totally our fault, I will fix the README 🍡

**Comment by hffmnn** [comment]
Running it with `ARTSY_STAFF_MEMBER=false pod install` gives the same result.

Maybe because `Artsy+UIFonts` is referenced in the lock file?

**Comment by orta** [comment]
can you try without `ARTSY_STAFF_MEMBER=false` at all please, just `pod install` - we check for [it's existence not it's value](https://github.com/artsy/emission/blob/master/Example/Podfile#L13)

**Comment by orta** [comment]
In Eigen we also have the `podfile.lock` referencing UIFonts but the UIOSSFonts _should_ override that here like it does there

**Comment by hffmnn** [comment]
A `pod install` gives me:

```
Analyzing dependencies
Pre-downloading: `Artsy+Authentication` from `https://github.com/artsy/Artsy-Authentication.git`, commit `1b582675598c999726d9edacd3b8559e01cf7c48`
Pre-downloading: `Artsy+UIFonts` from `https://github.com/artsy/Artsy-OSSUIFonts.git`
[!] Unable to find a specification for 'Artsy+UIFonts'.
```

A fresh clone of eigen and a `bundle exec pod install` gives:

```
bundle exec pod install
Analyzing dependencies
Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`
Removing ARASCIISwizzle
Removing DRKonamiCode
Downloading dependencies
Using AFNetworkActivityLogger (2.0.4)
Using AFNetworking (2.5.4)
Using AFOAuth1Client (0.4.0)
Using ALPValidator (0.0.3)
Using ARAnalytics (3.9.0)
Using ARCollectionViewMasonryLayout (2.1.2)
Using ARGenericTableViewController (1.0.2)
Using ARTiledImageView (1.2.0)
Using Adjust (4.5.0)
Using Aerodramus (0.1.0)
Using Analytics (3.0.7)
Using AppHub (0.5.1)
Installing Artsy+OSSUIFonts (2.0.2)
Using Artsy+UIColors (3.0.1)
Installing Artsy+UIFonts (1.1.1)
Username for 'https://github.com': 
```

**Comment by orta** [comment]
I've made a PR #421 ( it's only 2 LOC) want to see if those changes work when applied to your setup? We made some changes to the fonts stuff over the winter holidays and I don't think they've been applied here.

**Comment by hffmnn** [comment]
Thanks a lot for your help, but latest `master` (e9517860bef9f3ed76f87758dba1325f2897c2fc) gives:

```
Analyzing dependencies
Pre-downloading: `Artsy+Authentication` from `https://github.com/artsy/Artsy-Authentication.git`, commit `1b582675598c999726d9edacd3b8559e01cf7c48`
Fetching podspec for `Emission` from `../`
Fetching podspec for `React` from `../node_modules/react-native`
Downloading dependencies
Installing ARGenericTableViewController (1.0.2)
Installing AppHub (0.5.1)
Installing Artsy+Authentication (1.5.0)
Installing Artsy+UIColors (3.0.1)
Installing Artsy+UIFonts (1.1.1)
Username for 'https://github.com': 
```

**Comment by orta** [comment]
Thanks, hrm, alright, looks like I'll have to pretend to stop being an employee to figure this out

**Comment by hffmnn** [comment]
Soooo,

with [this](https://github.com/hffmnn/emission/commit/ae38c63e36c4500d0edf1424f92b8d3626f549f6) kind of brute-force approach (applied via [this](https://github.com/hffmnn/emission/commit/e2204ebf5c3a22c36b7946f8b3564fdc0d69c398)) I made cocoapods happy and could compile the project.  Obviously this should not be the solution (so I will not open a PR), but maybe it helps finding the problem/dependencies of `Artsy-UIFonts` for non-`ARTSY_STAFF_MEMBER`?

Aaand sorry: Next problem ahead:
After compiling and running the app (on the simulator) it asks me for my Artsy credentials (again 😄 ).
![simulator screen shot 17 jan 2017 19 37 19](https://cloud.githubusercontent.com/assets/352753/22034404/78b2a26c-dcec-11e6-8c64-67a65288f0e0.png)

Are there some `Anonymous` credentials? I re-read the `README`, but could not find any hint regarding this

**Comment by orta** [comment]
This would be an actual artsy account, though I guess you'd be on staging, so [change this](https://github.com/artsy/emission/blob/master/Example/Emission/AppDelegate.m#L64) we'd need to make sure that you're on the production API for OSS

Sign up link: https://www.artsy.net/sign_up

So, my TODO here:

- [ ] Add a `make oss` command
- [ ] Use production on OSS
- [ ] All this bizz https://github.com/artsy/eigen/issues/2088

**Comment by hffmnn** [comment]
Thank you very much! Works (kind of) perfect. I think the font based errors are a result of my brute force attempt to fix the `Artsy-UIFonts` issues?

![simulator screen shot 18 jan 2017 15 22 10](https://cloud.githubusercontent.com/assets/352753/22067553/0f700712-dd92-11e6-8c5f-8e144798a77e.png)

**Comment by orta** [comment]
Oh, hrm, that makes things even more complex

**Comment by orta** [comment]
- [ ] Edit OSS fonts to use the same font-family

**Comment by orta** [comment]
if you want to dare try it, you can replace the font files in Artsy-OSSFonts with the ones in here https://github.com/artsy/Artsy-OSSUIFonts/pull/7

They're the OSS fonts that have been modified to have the same names

**Comment by hffmnn** [comment]
Hi,

not 100% sure if I did everything correctly, but checked out `v3` at copied all assets into my `Pods` folder (inside the `Example`). Update all Assets (`Artsy+UIFonts` + `Artsy+OSSUIFonts`) and did NOT run any `pod` command after that. Still it gives me the same result. Did I miss anything?

**Comment by orta** [comment]
Sorry it took a while, but I've got all the pieces in place with #439 👍
