### ISSUE TITLE
Bug with ES6 bound function syntax

### ISSUE THREAD

**Issue by l2succes** [artsy/emission#428]
Hey guys,

I believe to have found a bug with the ES6 bound function property syntax (https://babeljs.io/docs/plugins/transform-class-properties/).
Might just be the babel implementation. This came about in the Artist component in emission. Any local variables constant or else defined outside of a bound function 
are captured/copied into the function scope. So any updated values aren't being picked up. This issue came about when I was testing hot reloading in emission, 
so it might be a bit of an edge case but thought I'd share in case you run into this as well.

To give a bit more context, I was trying to update `TABS.ABOUT` to some random string to see if it'd update. The value was updated in `render()` but not in the availableTabs() bound function.
We can probably still use the new syntax but just be mindful of that problem

```

const TABS = {
  ABOUT: 'ABOUT',
  WORKS: 'WORKS',
  SHOWS: 'SHOWS'
}

class Artist extends React.Component {
  instanceVar = {
    hello: 'world
  }

  ...
  availableTabs = () => {
    ...

    console.log("Tabs available tabs", TABS)
    console.log("localTabs (availableTabs)", Artist.instanceVar)

    if (displayAboutSection) {
      tabs.push(TABS.ABOUT)
    }

    if (artist.counts.artworks) {
      tabs.push(TABS.WORKS)
    }

    if (artist.counts.partner_shows) {
      tabs.push(TABS.SHOWS)
    }

    return tabs
  }
  ...

  render() {
    console.log("Tabs (render)", TABS)
    console.log("localTabs (render)", Artist.localTabs)

    return (

    )
  }
}
```

**Comment by alloy** [comment]
Let’s get rid of this class properties preset, it’s too experimental atm.

**Comment by orta** [comment]
Don't know if this exists in TS anyway TBH

**Comment by alloy** [comment]
Good point 👌
