### ISSUE TITLE
Integrate into Eigen

### ISSUE THREAD

**Issue by alloy** [artsy/emission#44]
- [x] Write switchboard bindings
- [x] Use proper loading spinner
- [x] Write artist follow API binding
- [x] Make Emission pod integration work in Eigen
- [x] Make Eigen+Emission setup smooth

**Comment by orta** [comment]
are the creation of view controllers synchronous?

**Comment by alloy** [comment]
The creation of the component host VC is, yeah, but you’ll see a spinner for as long as it’s requesting the initial data.

**Comment by orta** [comment]
makes sense, shouldn't be tough then, only thing to keep in mind is that pushes from a switchboard need to go back to `ARTopMenuVC sharedVC`'s `pushVC` or you could get crashes depending on the link
