### ISSUE TITLE
Switch all GETs to POSTs for Metaphysics

### ISSUE THREAD

**Issue by mzikherman** [artsy/emission#455]
We recently switched all Metaphysics requests in Force to use POST over GET. This helps with crazy long URLs, as well as logging (we don't usually log POST bodies).

Still seeing some `my_active_bids` queries using GET in the logs, not sure if that's coming from here? Or from Eigen?

Either way, we should use POSTs instead of GETs when communicating to Metaphysics.

**Comment by orta** [comment]
Eigen itself may do this in the auctions view controllers - @ashfurrow you know?

**Comment by alloy** [comment]
I’m unable to find this in either emission or eigen. Is there no user-agent in the logs?

**Comment by ashfurrow** [comment]
I'll check this morning 👍

**Comment by mzikherman** [comment]
Ah, sorry @alloy you're right :(

Looking at the logs more closely this morning reveals user agent and referrer on _some_ of these requests (which is Force's auction page). Not all of the GETs have this though 🤔 

There also seems to be fewer today than there was yesterday...since the auction page kicks these off every second I suspect some bidder/user out there has had an auction page open on their computer for....a while now  😞

**Comment by alloy** [comment]
Fun to hear that not having control over all deployed clients is not only an Eigen problem, even if in a drastically smaller amount :)

I’ll close this one and I assume you mean that the location this request was performed from has since been fixed (by your GET->POST refactor) ?

**Comment by mzikherman** [comment]
I think so, yea.

Though I guess I'm a bit unsure as to the state of Metaphysics use by iOS clients in prod...we should be using POSTs for those generally speaking (though I don't have any log evidence atm showing that). Up to you if there's anything to do or keep in mind for that stuff (Relay?).

**Comment by alloy** [comment]
We should be good, Relay did not use GET the last time I checked.

**Comment by ashfurrow** [comment]
Eigen does indeed use a GET: https://github.com/artsy/eigen/blob/master/Artsy/Networking/ARRouter.m#L1136 I'll send a PR to change.
