### ISSUE TITLE
Image shown as fully black

### ISSUE THREAD

**Issue by alloy** [artsy/emission#461]
Reported by @carterac.

![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/2320/24098244/d7769abc-0d69-11e7-9d7f-dd72ab7afff1.jpg)

**Comment by alloy** [comment]
Loading the individual artworks does show the image correctly.

**Comment by sarahscott** [comment]
I haven't seen this one in a long time - can I close this?

**Comment by alloy** [comment]
Let’s close it for now.
