### ISSUE TITLE
missing event for tapping search on home screen

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#481]
can't believe im only just realizing this but we've got no event instrumented for the big search bar on home

![image](https://cloud.githubusercontent.com/assets/6482926/24942256/bec07a4a-1f1d-11e7-8d34-4d750e177a18.png)

@anipetrov pls advise on schema/how you think we should implement, thanks!

**Comment by mennenia** [comment]
Good shout! This is probably going to go in [here](https://github.com/artsy/eigen/issues/2264)?
