### ISSUE TITLE
[WFU] Should always be opened on the bell tab

### ISSUE THREAD

**Issue by alloy** [artsy/emission#490]
By the end of this clip, the selected tab should have been the notifications tab.

![wfu-wrong-tab](https://cloud.githubusercontent.com/assets/2320/25307509/62146c92-27a2-11e7-85ca-cc32281fe539.gif)

**Comment by alloy** [comment]
This would also fix the presence of a back navigation button, which shouldn’t appear on the bell tab as this is the root view.

**Comment by sarahscott** [comment]
See https://github.com/artsy/eigen/pull/2307
