### ISSUE TITLE
[MSG] Update Inquiry Modal

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#492]
Updated inquiry modal should surface gallery response time, inquired on work and the pre-filled message body. 

Requirements 

- [ ] Gallery name
- [ ] Gallery response time
- [ ] Pre-filled text 
- [ ] Thumbnail of inquired on work 
- [ ] Send Button
- [ ] Network failure notification (perhaps we can save/send inquiry upon re-established connection)

![image](https://cloud.githubusercontent.com/assets/6482926/25832072/4d6e6d92-3436-11e7-8112-bc77b393c460.png)

**Comment by katarinabatina** [comment]
more details forthcoming

**Comment by alloy** [comment]
* Response time needs to be exposed from Impulse through MP: 1 day
* View building: 1 day

**Comment by tayapage6** [comment]
Issue moved to [artsy/collector-experience #298](https://github.com/artsy/collector-experience/issues/298) via [**ZenHub**](https://www.zenhub.com/)
