### ISSUE TITLE
[MSG] Attachment handling

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#493]
![image](https://cloud.githubusercontent.com/assets/6482926/25341518/11502c70-28d7-11e7-9007-4f30ede0debb.png)

**Comment by alloy** [comment]
The data for actual attachments (not necessarily invoices) is probably all there, but we’ll have to do some plumbing to expose it in the right way. 3 days

**Comment by tayapage6** [comment]
Issue moved to [artsy/collector-experience #297](https://github.com/artsy/collector-experience/issues/297) via [**ZenHub**](https://www.zenhub.com/)
