### ISSUE TITLE
[MSG] Gallery Info 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#494]
Likely not a release requirement for first version of messaging

Requirements 

- [ ] Gallery name
- [ ] Gallery locations
- [ ] Gallery description
- [ ] Gallery response time
- [ ] Call gallery button

![image](https://cloud.githubusercontent.com/assets/6482926/25832329/e392ff80-3437-11e7-8998-332d45cfc208.png)

**Comment by alloy** [comment]
1 day

**Comment by tayapage6** [comment]
Issue moved to [artsy/collector-experience #296](https://github.com/artsy/collector-experience/issues/296) via [**ZenHub**](https://www.zenhub.com/)
