### ISSUE TITLE
[MSG] Inbox

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#495]
Requirements 

- [ ] Zero state promoting how collecting on Artsy works
- [ ] Message line items (including gallery name, artists name, work title, message blurb)
- [ ] Thumbnail of inquired on artwork 
- [ ] Message time stamp
- [ ] read/unread state

![image](https://cloud.githubusercontent.com/assets/6482926/25366557/7e1d51d6-293e-11e7-9769-011b34d55775.png)

**Comment by alloy** [comment]
* Landing page: 4 hours
* Layout of message list: 4 hours
* We can already fetch inquiries, as part of our loyalty program work.
* But for read/unread state and excerpt of _latest_ message we might need to add a connection to MP for Impulse’s conversations: 2 days

Total: 3 days

**Comment by katarinabatina** [comment]
follow up with detail about how how list should be sorted

**Comment by alloy** [comment]
We need to make sure that we ask Impulse for messages that are not marked as spam (e.g. partner newsletters).

**Comment by tayapage6** [comment]
Read/unread might be more accurate if we used "opened on this app" v "not yet opened" given that impulse only knows that SOMEONE opened it (could be a gallery employee cced)

**Comment by tayapage6** [comment]
Issue moved to [artsy/collector-experience #295](https://github.com/artsy/collector-experience/issues/295) via [**ZenHub**](https://www.zenhub.com/)
