### ISSUE TITLE
[MSG] Message/Composer

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#496]
Requirements

- [ ] Gallery name (Gallery should be considered as one entity with no consideration as to who the sender is, different from how we handle this in CMS)
- [ ] Timestamp
- [ ] Message content 
- [ ] Composer
- [ ] Composer error states (failure to send message/retry)

![image](https://cloud.githubusercontent.com/assets/6482926/25367032/5f4f7b46-2941-11e7-9834-978146c487b2.png)

**Comment by alloy** [comment]
* Most of the UI should already exist from other tickets + error state handling: 1 day
* We may need to modify/create a specific endpoint on Impulse to send a message: 2 days

**Comment by katarinabatina** [comment]
create separate ticket around email edge cases and how to represent them in the native chat view

**Comment by tayapage6** [comment]
Issue moved to [artsy/collector-experience #294](https://github.com/artsy/collector-experience/issues/294) via [**ZenHub**](https://www.zenhub.com/)
