### ISSUE TITLE
Recommended for you rail showing with no results, should be hidden

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#506]
![img_4400](https://cloud.githubusercontent.com/assets/6482926/25717926/26324468-30d2-11e7-8c48-5d570e86bbba.PNG)

**Comment by mzikherman** [comment]
I am not sure what this is. I suspected on Friday that this was a caching issue: the endpoint that checks _if_ this rail should show up is now uncached and 'live', whereas the endpoint that returns the data for the rail might have been cached.

However, they both should be equivalently cached now, and a spec trying to repro the above hypothesis didn't work, so I'm stumped 🤔 

@katarinabatina does this issue still persist?

**Comment by katarinabatina** [comment]
@mzikherman yup I still have it today

**Comment by mzikherman** [comment]
Added a spec/repo: https://github.com/artsy/gravity/pull/11032

I'm stumped :(

**Comment by mzikherman** [comment]
Added a spec/repo: https://github.com/artsy/gravity/pull/11032

I'm stumped :(

**Comment by sarahscott** [comment]
This might be fixed by https://github.com/artsy/emission/pull/529; if the data actually isn't ever being fetched than it will be fixed by my next pr.

**Comment by alloy** [comment]
This is done
