### ISSUE TITLE
Single artist work rail showing as empty, artist has works for sale

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#507]
![img_4409](https://cloud.githubusercontent.com/assets/6482926/25717958/4508440a-30d2-11e7-8b41-b73c1711b30e.PNG)

**Comment by mzikherman** [comment]
We do have a blanket 50 minute cache on the ElasticSearch endpoint (for performance). So, it's possible that an artist that just had some newly published works might show up as blank for a short while. 

@katarinabatina is this still happening?

**Comment by katarinabatina** [comment]
not currently but maybe we should be handling these situations better on the client? If there's nothing don't show the rail?

**Comment by mzikherman** [comment]
@alloy might have an opinion, but on Force we do have a 'catch-all' to hide the rail if there are no actual results for it (https://github.com/artsy/force/blob/3f95087005fdd3c63e48183c8de96f01099d67fe/desktop/apps/home/client/setup_home_page_modules.coffee#L73). That seems to work well in some of these edge-cases.

**Comment by alloy** [comment]
We should totally do the same thing. @l2succes wanna take this?

**Comment by sarahscott** [comment]
This is fixed by https://github.com/artsy/emission/pull/529
