### ISSUE TITLE
repeat rails in feed

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#515]
![image](https://cloud.githubusercontent.com/assets/6482926/25812496/8115d830-33e4-11e7-81d7-9722afa0f5e2.png)

![image](https://cloud.githubusercontent.com/assets/6482926/25812507/87e0706c-33e4-11e7-8d63-f17c2ccff5d8.png)

**Comment by sarahscott** [comment]
Is this on production? And is it still reproducible?

**Comment by alloy** [comment]
I think there’s sub-genes that are named the same but are subsets, maybe that’s happening here?

**Comment by sarahscott** [comment]
Can't reproduce
