### ISSUE TITLE
Support showing stories inside the Emission beta

### ISSUE THREAD

**Issue by orta** [artsy/emission#562]
Right now stories are controlled entirely from an external website, in theory we could expose that and allow you to connect the beta to it, but that's pretty inelegant and no-one will do it.

E.g. _only this_ is bad
![screen shot 2017-05-24 at 10 31 08](https://cloud.githubusercontent.com/assets/49038/26396787/213383c4-406c-11e7-9604-9739d803cf18.png)

Ideally there'd be a normal UITableView with all the top level, then low levels.

What could work instead is that we make a new component that makes a list of all stories and lets you choose them in-app.

**Comment by orta** [comment]
Gave myself a few minutes to explore this, should be pretty feasible from the browsing aspect

```js
import { getStorybook } from "@storybook/react-native"

// In some place to call the code
console.log("HIII")}
console.log(getStorybook())
```
Looks like

![screen shot 2017-05-24 at 10 50 48](https://cloud.githubusercontent.com/assets/49038/26397665/fa55ee2e-406e-11e7-8600-573590b8f246.png)

**Comment by orta** [comment]
We don't ship the stories with the production JS, so these can only exist inside the emission side of the codebase.

**Comment by alloy** [comment]
@orta this is done, right?

**Comment by orta** [comment]
Yep
