### ISSUE TITLE
Convert Consignments TODO / Artist Search to PureComponents

### ISSUE THREAD

**Issue by orta** [artsy/emission#566]
> There are 2 primary methods for writing stateless components in React: the PureComponent class and functions. Functions are simpler, but they render on every reconciliation which can hurt performance. The React team has plans to optimize functions, but for now it seems best to avoid them. We chose instead to use PureComponent, which includes a predefined shouldComponentUpdate method that prevents updates when passed identical props.

[source](https://slack.engineering/rebuilding-slacks-emoji-picker-in-react-bfbd8ce6fbfe)

Worth a quick look, better to do this now instead of further down the line when they're more complicated and people are using it as an example of best practices

**Comment by alloy** [comment]
Nice catch 👍 

/cc @sarahscott @l2succes

**Comment by orta** [comment]
Took a quick look, it could work by moving them from this:

```js
export default (props: ArtistQueryData) =>
  <View>

    <View style={{flexDirection: "row"}}>
      <Input
        autoFocus={true}
        onChangeText={props.textDidChange}
        defaultValue="Artist/Designer Name"
        keyboardAppearance="dark"
        placeholderTextColor={ colors["gray-medium"] }
        autoCorrect={false}
        value={props.query}
        selectionColor={ colors["gray-medium"] }
      />
      <ActivityIndicator animating={props.searching} />
    </View>

    <Separator/>

    <ScrollView style={{height: 182, paddingTop: 16}} scrollEnabled={props.results && !!props.results.length}>
      {props.results && props.results.length ? props.results.map(rowForResult) : noResults(props) }
    </ScrollView>

    <Separator/>
    <View style={{height: 40}}>
      <Button text="DONE" />
    </View>
  </View>
```

To this:

```js
const render = (props: ArtistQueryData) =>
  <View>

    <View style={{flexDirection: "row"}}>
      <Input
        autoFocus={true}
        onChangeText={props.textDidChange}
        defaultValue="Artist/Designer Name"
        keyboardAppearance="dark"
        placeholderTextColor={ colors["gray-medium"] }
        autoCorrect={false}
        value={props.query}
        selectionColor={ colors["gray-medium"] }
      />
      <ActivityIndicator animating={props.searching} />
    </View>

    <Separator/>

    <ScrollView style={{height: 182, paddingTop: 16}} scrollEnabled={props.results && !!props.results.length}>
      {props.results && props.results.length ? props.results.map(rowForResult) : noResults(props) }
    </ScrollView>

    <Separator/>
    <View style={{height: 40}}>
      <Button text="DONE" />
    </View>
  </View>

// Export a pure component version
export default class SearchResults extends React.PureComponent<ArtistQueryData, null> {
  render() { return render(this.props) }
}
```

Still get the syntax advantages, and simplicity of the function-based component, but also get the runtime advantages with a few extra lines.

**Comment by orta** [comment]
A useful danger rule on new app tax files could be a warning on if the new files include the string `PureComponent`.

**Comment by alloy** [comment]
I don’t follow why we’d not simply want to move all of it into the `PureComponent` subclass then?

**Comment by orta** [comment]
Mainly:

* Encourages using more, smaller functional components
* Actual code further away from the golden path ;)
* Have to wrap JSX in `()` as you can't use fat arrow functions for render
* Eventually we can just delete the PureComponent part

**Comment by orta** [comment]
Related: https://flexport.engineering/optimizing-react-rendering-part-1-9634469dca02
