### ISSUE TITLE
[Gene] Refine by medium not working

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#578]
To repro:

1. Open any gene
2. Tap Refine
3. Select a medium

Works of all mediums are still shown; there doesn't seem to be any filtering.

**Comment by katarinabatina** [comment]
@orta @alloy is this a dupe? has it bee picked up yet?

**Comment by orta** [comment]
Can confirm this is legit.

I did fix the refine button in general though, looks like the main content isn't replaced, pagination seems to respect the new settings

**Comment by sarahscott** [comment]
I'm not seeing filtration in the pagination results either.

**Comment by orta** [comment]
The JSON returned seems to fit with what we'd expect after filtering

<img width="1415" alt="screen shot 2018-01-08 at 10 42 16 am" src="https://user-images.githubusercontent.com/49038/34678277-aa91da46-f460-11e7-94e0-0ee650497fa0.png">

**Comment by orta** [comment]
In migrating to relay modern the second param (callback) was left empty after the refetch, could this mean that state isn't being changed by relay but should be done manually?

https://github.com/artsy/emission/blob/a91d86646b8745bc21cb80356ae4d8057ae07a60/src/lib/Containers/Gene.tsx#L195-L206

**Comment by alloy** [comment]
You need to manually call `setState` to e.g. show a spinner and remove it from the callback, but if the data Relay fetches changes I would assume that to trigger a re-render as the props change.

**Comment by orta** [comment]
Initial query variables 

![screen shot 2018-01-08 at 11 11 04 am](https://user-images.githubusercontent.com/49038/34679668-a8c9fb04-f464-11e7-9f76-8206676f881b.png)

Hit refine:

![screen shot 2018-01-08 at 11 11 36 am](https://user-images.githubusercontent.com/49038/34679685-b83ad87e-f464-11e7-945b-581e703b57a1.png)

Pagination triggered by the artworks grid after that
![screen shot 2018-01-08 at 11 12 01 am](https://user-images.githubusercontent.com/49038/34679700-c45cc68a-f464-11e7-9c2f-62c10c24ad55.png)

I wonder if the state isn't being passed down

**Comment by orta** [comment]
Looking like the arguments are always falling back to the default ones in the pagination argument definition

https://github.com/artsy/emission/blob/a91d86646b8745bc21cb80356ae4d8057ae07a60/src/lib/Components/ArtworkGrids/RelayConnections/GeneArtworksGrid.tsx#L9-L21

**Comment by orta** [comment]
This feels like two bugs:

* Changing the refine settings isn't resetting the artworks grid (new props are definitely being sent down though)
* Appends coming from the `InfiniteScrollArtworksGrid` don't have query vars set

it looks like the initial Gene query passes through the query params correctly, but once it gets into requests being made by adding them to `getVariables`

```js
    getVariables(props, { count, cursor }, _fragmentVariables) {
      return {
        __id: props.gene.__id,
        count,
        cursor,
        sort: props.sort,
        medium: props.medium,
        priceRange: props.priceRange,
      }
    },
```

This then brings up an error message I've not quite got to the root of yet:

```
Warning: RelayConnectionHandler: Unexpected after cursor `YXJyYXljb25uZWN0aW9uOjI=`, edges must be fetched from the end of the list (`YXJyYXljb25uZWN0aW9uOjEy`).
reactConsoleErrorHandler @ ExceptionsManager.js:73
console.error @ YellowBox.js:67
printWarning @ warning.js:33
warning @ warning.js:57
update @ RelayConnectionHandler.js:107
(anonymous) @ RelayPublishQueue.js:168
```

**Comment by alloy** [comment]
I always forget what `fragmentVariables` is, but maybe that’s the variables that the query was originally rendered with and so you need to first spread that into your return object and then override whatever you need to?

**Comment by orta** [comment]
Started looking at the issue of the initial query being wrong because it doesn't have the default variables.

The initial query `Gene_gene` doesn't set the variables for it's artwork

![screen shot 2018-01-09 at 11 42 14 am](https://user-images.githubusercontent.com/49038/34732092-3681affa-f532-11e7-8d15-996be3ea1fcb.png)

Infact it inlines the default values and skips a query value entirely.

A hack: updating `componentWillMount` to set the right relay variables:

```js
  componentWillMount() {
    this.state = {
      selectedTabIndex: 0,
      showingStickyHeader: true,

      // Use the metaphysics defaults for refine settings
      sort: "-partner_updated_at",
      selectedMedium: this.props.medium || "*",
      selectedPriceRange: this.props.price_range || "*-*",
    }
    this.props.relay.refetch({
      sort: this.state.sort,
      medium: this.state.selectedMedium,
      price_range: this.state.selectedPriceRange,
    })
  }
```

In the Gene it works but it has to be done after a full fetch cycle is done.

**Comment by orta** [comment]
I read through relay's source and it does imply that these variables get set via the props

https://github.com/facebook/relay/blob/d28119ad3284e632632f7eb96d35f3eb27b90d6a/packages/react-relay/modern/ReactRelayRefetchContainer.js#L202-L210

but the props passed in from the QeuryRender are correct:

https://github.com/artsy/emission/blob/a91d86646b8745bc21cb80356ae4d8057ae07a60/src/lib/relay/QueryRenderers.tsx#L106-L128

![screen shot 2018-01-09 at 11 47 24 am](https://user-images.githubusercontent.com/49038/34732303-e26b9dee-f532-11e7-991c-3ca4c9a5c65f.png)

So I don't see why they're not b being used inside the query
