### ISSUE TITLE
Should we request resized images from metaphysics upon rotation for iPad?

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#58]
Currently, rotation looks like:

![ipadrelatedartistsrotate](https://cloud.githubusercontent.com/assets/2712962/15261776/539c43cc-192c-11e6-96cb-84f47be31295.gif)

![shows_ipad_rotation](https://cloud.githubusercontent.com/assets/2712962/15261778/55a7bcfa-192c-11e6-9f30-dbccb5931de0.gif)

**Comment by alloy** [comment]
Fixed by #146.
