### ISSUE TITLE
[MSG] Artwork preview component 

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#610]
![screen shot 2017-06-12 at 4 18 48 pm](https://user-images.githubusercontent.com/2712962/27038296-d75d1980-4f8a-11e7-8cca-7f9b9d30e81d.png)

**Comment by sarahscott** [comment]
@katarinabatina should the title truncate or push the date to a new line?

<img width="380" alt="screen shot 2017-06-12 at 5 40 49 pm" src="https://user-images.githubusercontent.com/2712962/27042181-8149de14-4f96-11e7-9d7d-77072a62ef9a.png">

**Comment by katarinabatina** [comment]
@sarahscott good question, please truncate. Also note that the info tab will not be pursued for V1 so feel free to eliminate the button for it.

**Comment by sarahscott** [comment]
Fixed by #614
