### ISSUE TITLE
[MSG] Network connectivity states in Composer

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#625]
UI + Relay handling of:
- [x] Successful message send
- [x] Unsuccessful send
- [x] Unsuccessful fetch
- [ ] ~~Local storage~~ We decided not to make this part of the MVP

![](https://cloud.githubusercontent.com/assets/6482926/26464297/46a042c0-4155-11e7-8447-9363b520ac44.png)

**Comment by alloy** [comment]
For the MVP we settled on the following. On _any_ failure:

* remove the optimistic message
* restore the text into the textfield

**Comment by alloy** [comment]
@sarahscott The changes in #757 don’t fully implement the requested design in this ticket. Maybe discuss the differences with Katarina and then decide whether to create new tickets for iterations or how else to proceed.

**Comment by sarahscott** [comment]
Doesn't #757 implement the MVP comment above?

**Comment by alloy** [comment]
It sure does! But not the original requirements, so before we lose track of that, only for it to be resurfaced by Katarina during QA, let’s make sure we’re all aware of it _now_.

**Comment by sarahscott** [comment]
Sounds good. I guess for posterity we can say that maintaining failed messages would require some sort of local storage, and that's why we decided on the textfield solution for now.

**Comment by tayapage6** [comment]
Note from standup - if there is one pending message, another cannot be sent (send button disabled)

**Comment by alloy** [comment]
For the MVP we decided to still have the yellow ‘pending’ message.
