### ISSUE TITLE
[MSG] Attachment download progress indicator.

### ISSUE THREAD

**Issue by alloy** [artsy/emission#638]
From https://github.com/artsy/emission/pull/636

It’s especially lacking a download progress indicator for when an attachment has not yet been cached. I was thinking of a circular masked progress indicator (which I _think_ WhatsApp uses?) that would overlay the attachment component, something like [this](http://cl.ly/DxLM) except not as a window-wide modal, however that probably wouldn’t work well for PDF components (unless we’d preview those too).

@katarinabatina can you give some thought into what this should look like?

**Comment by alloy** [comment]
We currently have a very simple purple bar at the top of the attachment:

![simulator screen shot 10 jul 2017 13 55 10](https://user-images.githubusercontent.com/2320/28017039-6fe2c27a-6577-11e7-8b01-6af0d6804002.png)

![simulator screen shot 10 jul 2017 14 08 44](https://user-images.githubusercontent.com/2320/28017380-4c33211a-6579-11e7-8d34-865c8c01e687.png)

**Comment by katarinabatina** [comment]
@alloy does this loading state show once I tap the image or attachment or upon viewing them in the thread?

**Comment by alloy** [comment]
Once you tap the image/attachment, but only if it wasn’t downloaded and cached before.

**Comment by alloy** [comment]
@katarinabatina Do you want to have a custom one or are you happy with the current one?

**Comment by katarinabatina** [comment]
@alloy think we're good for now, will open new ticket if feeling like we need a change
