### ISSUE TITLE
[MSG] Fix text size and vertical alignment in Composer

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#639]
- [x] "Reply..." should be vertically aligned with SEND button
- [x] Font size should be a bit bigger

<img width="384" alt="screen shot 2017-07-05 at 08 24 12" src="https://user-images.githubusercontent.com/2712962/27871726-63bcb8b8-615b-11e7-9e56-59a4ed3b6869.png">

**Comment by l2succes** [comment]
Fixed with https://github.com/artsy/emission/pull/641
