### ISSUE TITLE
[MSG] Composer doesn't move up with keyboard

### ISSUE THREAD

**Issue by l2succes** [artsy/emission#640]
![simulator screen shot jul 6 2017 10 48 44 am](https://user-images.githubusercontent.com/296775/27918615-7aa06ab0-623d-11e7-90d9-50f2b09b3fae.png)

**Comment by orta** [comment]
I use a keyboard avoiding view in Consignments for this: https://github.com/artsy/emission/blob/master/src/lib/Components/Consignments/Components/BottomAlignedButton.tsx#L36
