### ISSUE TITLE
[MSG] Conversation scrolling

### ISSUE THREAD

**Issue by alloy** [artsy/emission#642]
- [ ] Paginate _up_ to see older messages.
- [ ] Pull _up_ at the end of the bottom of the list to refresh.
- [ ] Initially messages should stick to the top of the scrollview.
      <img width="312" alt="screen shot 2017-07-05 at 3 40 41 pm" src="https://user-images.githubusercontent.com/2320/27930665-bb5c5924-6297-11e7-8da8-23f7a170e2bd.png">

**Comment by tayapage6** [comment]
Issue moved to [artsy/collector-experience #486](https://github.com/artsy/collector-experience/issues/486) via [**ZenHub**](https://www.zenhub.com/)
