### ISSUE TITLE
[MSG] Pull to refresh control is shown when loading the Inbox

### ISSUE THREAD

**Issue by alloy** [artsy/emission#646]
When opening the Inbox view, we immediately show the pull to refresh control. Because in most cases this won’t actually load (much) new data the control almost immediately hides again, which makes the overall experience one that makes the list appear to bounce.

The pull to refresh control should _only_ be shown when the user initiates a pull to refresh.

**Comment by l2succes** [comment]
FIxed with https://github.com/artsy/emission/issues/649
