### ISSUE TITLE
[MSG] Inbox Pull-To-Refresh animation is a bit strange

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#653]
Sometimes subtle:

![bouncy](https://user-images.githubusercontent.com/2712962/27973343-96065842-630e-11e7-88d8-121163f345d3.gif)

Sometimes extra bouncy:

![bouncy](https://user-images.githubusercontent.com/2712962/27974358-9259c464-6312-11e7-8f76-463178d554f3.gif)

**Comment by alloy** [comment]
This _may_ be fixed by #664, should test that when beta 3 is out.

**Comment by alloy** [comment]
Not seeing this.
