### ISSUE TITLE
[MSG] Message with an invoice attached/embedded looks weird

### ISSUE THREAD

**Issue by mzikherman** [artsy/emission#654]
<img width="356" alt="screen shot 2017-07-07 at 12 52 14 pm" src="https://user-images.githubusercontent.com/1457859/27975693-4a51ee34-6331-11e7-84fe-b024332e1d0f.png">

(we have `is_invoice` in metaphysics so likely we can format/do something else) + invoice handling design comp

**Comment by alloy** [comment]
Closing in favour of #445.
