### ISSUE TITLE
[MSG] Truncate purchase request messages (why are we even getting the receipt)?

### ISSUE THREAD

**Issue by mzikherman** [artsy/emission#655]
We already handle `About the collector:` type sanitization, we should handle this one too:

<img width="355" alt="screen shot 2017-07-07 at 12 14 53 pm" src="https://user-images.githubusercontent.com/1457859/27975736-69d46ca0-6331-11e7-8289-73f06cdd91e3.png">

(possibly other types? check with @ashkan18 for code/deetz)

**Comment by alloy** [comment]
Implementation is probably dependent on what we decide to use [to cleanup emails](TODO).

**Comment by mzikherman** [comment]
This seems like some sort of weird bug, there's a link to the CMS conversation. This is a receipt to the partner that somehow went to the user?

We should look into why/whats happening with purchase requests.

**Comment by mzikherman** [comment]
Done, we have `original_text` now.
