### ISSUE TITLE
[MSG] Very long text message doesn't render

### ISSUE THREAD

**Issue by mzikherman** [artsy/emission#656]
It's just an empty box, sorta acts up in the simulator. I copy-pasted a long short story in as the message- CMS renders it alright.

<img width="364" alt="screen shot 2017-07-07 at 11 53 30 am" src="https://user-images.githubusercontent.com/1457859/27975748-88cf9440-6331-11e7-9a9f-9f20c827a652.png">

**Comment by alloy** [comment]
Works on device 👍
