### ISSUE TITLE
[MSG] Detect/sanitize when there's forwarded content

### ISSUE THREAD

**Issue by mzikherman** [artsy/emission#657]
<img width="362" alt="screen shot 2017-07-07 at 11 40 26 am" src="https://user-images.githubusercontent.com/1457859/27975764-9924847c-6331-11e7-8aad-99d8bf6ebfe4.png">

We can truncate `~~~~~Forwarded message~~~~~~` type thing?

**Comment by alloy** [comment]
This needs re-checking now that we’re no longer using `raw_body`.

**Comment by tayapage6** [comment]
@mzikherman did this get checked per alloy's comment above?

**Comment by mzikherman** [comment]
Looks pretty good w/ the new sanitization library, just the `~~ Forwarded Message ~~` is displayed.
<img width="360" alt="screen shot 2017-07-27 at 5 01 44 pm" src="https://user-images.githubusercontent.com/1457859/30190867-1fe7138a-940b-11e7-8eb4-81c9ca6f67c2.png">
