### ISSUE TITLE
[MSG] Also support partner show inquiries.

### ISSUE THREAD

**Issue by alloy** [artsy/emission#672]
Currently we’re also surfacing conversations that centre around `PartnerShow` inquiries (which are limited to fair booths atm).

**Comment by alloy** [comment]
Seeing as Impulse doesn’t support filtering by type, and @ashkan18 indicated that could be cumbersome, it makes more sense to support these too.

**Comment by ashkan18** [comment]
I can imagine with https://github.com/artsy/impulse/pull/283 change in, it should be easier to support partner shows, ideally there would be minimal(if any) logic on clients to deal with Artwork vs. PartnerShow

**Comment by alloy** [comment]
This is not going to make it for today’s beta.

**Comment by ashkan18** [comment]
@alloy if you think its useful we can merge that PR and once we decided on Impulse changes we can cleanup if needed, whichever makes more sense to you.

**Comment by alloy** [comment]
It’s not that critical to make changes around this during these betas, as long as we come to a final implementation before the final beta.

**Comment by mzikherman** [comment]
Done'd!
