### ISSUE TITLE
Composer Interface Tweaks

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#677]
Remaining work: Nice 1px solid separator line. Japanese dots sent back to the icebox as a universal design component.

------

Type size of user labels appears to be 9 or 10px, should be 11px
![image](https://user-images.githubusercontent.com/6482926/28098116-6ba6fa80-6682-11e7-9742-d0da45efb351.png)

Sketch makes it hard to express "Japanese dots" as a line quality but outlined here is the desired dotted line versus what we have now 
![image](https://user-images.githubusercontent.com/6482926/28098204-f0b6f658-6682-11e7-985e-316f1e4c19aa.png)

 time stamp and user spacing 
![image](https://user-images.githubusercontent.com/6482926/28098298-7c03f3dc-6683-11e7-91da-1559b8fc4f58.png)

**Comment by mennenia** [comment]
@katarinabatina 

so the font is actually 11pt... I tried changing it to 12, but then it looks too big, so I settled on 11.5, which looks a bit like what you're going for. 

Do I then also change the "date" label to the larger font? Currently, the timestamp looks a bit off compared to the name:

<img width="325" alt="screen shot 2017-07-14 at 14 48 59" src="https://user-images.githubusercontent.com/373860/28214801-97164f68-68a3-11e7-8eb1-299bc11d6a12.png">

Spacing has been fixed ☑️ 

The dotted line thing looks like it's impossible in react native, at least from CSS. Even the dotted style we're using, are actually just a bunch of squares :/. You cannot specify the gap between them unfortunately.

I can probably create a custom view where we create a bunch of miniature circles, and line them up, etc. I don't know much about the performance impact of this approach, but I can check further. I would probably leave that for a bit later though, if that's ok?

**Comment by katarinabatina** [comment]
@mennenia yes change for time stamp too

bloomberg uses these dotted lines a lot, I feel like there's gotta be a baseline css style that allows us to do this? https://www.bloomberg.com/markets

Maybe it's about making the rule "less than a pixel" ?

**Comment by mennenia** [comment]
Sorry, I should have clarified: it exists in web CSS, but there's only select CSS styles that RN makes available and can transform into iOS components and views. RN is also in control what a style then translates to or appears as. 

In this case, `border-style` exists for both RN and web. We [set the border to dotted](https://github.com/artsy/emission/blob/master/src/lib/Containers/Conversation.tsx#L50), and I have no further properties or control as to what that then looks like (which is the square like, frequent, dot we see).

I have played with all the properties available, changed the sizing (also tried making it less than a pixel), but generally it either stays the same, becomes really thin so it essentially looks like a line, or disappears (when I only try to stroke the top or bottom). 

I had a look how to do this in iOS too, and the default is dashed. You have to faff a little bit to make it rounded, but it's very doable in core graphics. Perhaps we could make a native component for the line. @alloy?

**Comment by sarahscott** [comment]
Yeah a native component seems like the way to go if we have to space out the dots - rendering a bunch of tiny circles in pure RN seems cumbersome.

**Comment by alloy** [comment]
Agreed

**Comment by alloy** [comment]
This is marked as an Easy First Task, but does involve working with (Objective-)C and probably the CoreGraphics framework. If you do have some (Objective-)C experience, feel free to ping me to pair on the implementation.

**Comment by alloy** [comment]
It’s a doner! @erikdstock :clap:

**Comment by izakp** [comment]
🥙 ?

**Comment by orta** [comment]
:trollface:

**Comment by alloy** [comment]
OH MY GOD! Yes!

**Comment by mennenia** [comment]
👏
