### ISSUE TITLE
[MSG] Pending state in Messages

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#684]
Part of #625 

![screen shot 2017-07-13 at 4 39 51 pm](https://user-images.githubusercontent.com/2712962/28192286-ea7b3f52-67e9-11e7-85ee-e822977be172.png)

**Comment by alloy** [comment]
@sarahscott Is this done yet?

**Comment by sarahscott** [comment]
Nope, was hoping for some IRL pair programming on this one 😄

**Comment by tayapage6** [comment]
@sarahscott given this being marked as P0 and our agreement to not cache any content for MVP I'm going to move this back to the icebox... is there anything already in progress for this that needs to be wrapped up?
