### ISSUE TITLE
[MSG] Long delay before conversations get sorted correctly in Inbox

### ISSUE THREAD

**Issue by l2succes** [artsy/emission#762]
If you send a new message in conversation and go back to the Inbox view, the message won't jump to the top right away. In this case, it took about 4 minutes. The 4th conversation in the list should be at the top of the Inbox.

<img src="https://user-images.githubusercontent.com/296775/30609114-78d4ac50-9d48-11e7-8871-eb4a92742be1.png" width="300" />

**Comment by alloy** [comment]
Also, what’s that warning about?

**Comment by l2succes** [comment]
It shows up when you do a pull to refresh, it has to do with the InboxRefetchQuery not including a `cursor` and `count`. It's probably just a matter of adding those to the query.

**Comment by alloy** [comment]
I’m not even sure why the inbox would reload at all. Do you know why?

**Comment by katarinabatina** [comment]
@alloy this ticket seems a bit out of date, I'm not seeing anything noticeable when refreshing the inbox view..something we can close?

**Comment by alloy** [comment]
Probably. @l2succes can you reopen if there’s still a problem?
