### ISSUE TITLE
[MSG] Initial inquiry message not getting sanitized

### ISSUE THREAD

**Issue by l2succes** [artsy/emission#763]
Everything after and including *About this collector:* should be removed from the message but it's still in there

<img src="https://user-images.githubusercontent.com/296775/30614267-d52b9daa-9d58-11e7-9cfe-c8e144ae8733.png" width="320" />

cc @mzikherman

**Comment by sarahscott** [comment]
We decided to move the sanitization to MP, right? It used to be in Emission but was removed in #721

**Comment by l2succes** [comment]
Yeah, we were using the wrong `text` variable in emission which made it seem like the message weren't getting sanitized. It's been fixed with https://github.com/artsy/emission/pull/767
