### ISSUE TITLE
Payment Request view collapses after scrolling up to another page

### ISSUE THREAD

**Issue by l2succes** [artsy/emission#764]
The payment request components look fine and have the correct height on initial load. However, after scrolling up and loading the next set of message the container get collapsed (height = 0)

Before scrolling up to another page:
<img src="https://user-images.githubusercontent.com/296775/30616672-08bb2ce6-9d61-11e7-94d1-87c461ffd7f9.png" width="320" />

After scrolling up to another page:
<img src="https://user-images.githubusercontent.com/296775/30616640-e81b4d18-9d60-11e7-9bf4-bd967313a520.png" width="320" />

**Comment by mzikherman** [comment]
Yes, thank you! I was going to make an issue for this...was just noticing the subsequent pagination -> weirdo render. Weiiird
