### ISSUE TITLE
How do you work on Emission within eigen?

### ISSUE THREAD

**Issue by k0nserv** [artsy/emission#774]
Say you wanted to work with Emission inside a development version of Eigen running locally? Is this a use case you see and if you do how do you do it? Seems to me that since you ship bundled JS in Emission this development experience wouldn't be that good?

**Comment by sarahscott** [comment]
Hey there! Great question - see [these docs](https://github.com/artsy/emission/blob/master/docs/running-emission-in-eigen.md).

**Comment by k0nserv** [comment]
Cool 👍 Thanks for the quick reply. Per the docs it seems like something you don't do that often. How's the development experience when you do use it?

**Comment by sarahscott** [comment]
It can be a bit cumbersome but we usually only need to do this toward the end of feature development, so at least for me, it's not a bad experience because it's not very often. And it only takes a few minutes.

**Comment by k0nserv** [comment]
Interesting, thanks for the response I'll mull it over a bit for our usecase. I suspect we won't have the same luxoury in terms of isolation that you do.

**Comment by sarahscott** [comment]
Completely understandable. We’d also like to have this process be more smooth and work more in the context of Eigen, so if you do have some ideas please do share them with us!

**Comment by k0nserv** [comment]
Definitely will do 👍
