### ISSUE TITLE
Make sure we upgrade to RN 0.50.0 before next release

### ISSUE THREAD

**Issue by sarahscott** [artsy/emission#797]
It includes a [very important fix](https://github.com/facebook/react-native/issues/1831#issuecomment-336552156) for the blank scrollview issue. We have dealt with this in the meantime by injecting code through the Podfile (https://github.com/artsy/eigen/pull/2440).

Also see https://github.com/artsy/eigen/issues/2439

If it's not possible to upgrade to 0.50.0, we at least need to add a patch for the `RCTView` fix.

**Comment by alloy** [comment]
Also port changes from https://github.com/artsy/emission/pull/798 to master and include in our major release.

**Comment by katarinabatina** [comment]
@sarahscott please add note

**Comment by sarahscott** [comment]
Patchy fix in https://github.com/artsy/eigen/pull/2440

We can hold off on updating for now unless we see the blank scrollview again.
