### ISSUE TITLE
Consignments Flow Feedback

### ISSUE THREAD

**Issue by ashfurrow** [artsy/emission#802]
Took a look at the submission flow – great work! I've got some feedback, feel free to break these into separate tickets.

- Category field can't be selected, pressing "return" while in the previous field dismisses the keyboard.
- Metadata view's done button is obscured by keyboard until dismissed.
- Width/height keyboards should be number-keyboards by default.
- The inches/centimetres switch changes colour based on the unit, which seems weird. cm looks "on" and in looks "off" – intentional?
- Artist name field should autocapitalize each word.
- Partially filled-in metadata appears empty from overview view (the plus sign is still there instead of a checkmark).
- Text cursor on provenance view is not vertically centred with placeholder text.
- Text-selection caret is very difficult to invoke on the provenance view, making cut/copy/paste difficult.
- Pressing "Next" didn't do anything for me (on the most recent Emission beta)

**Comment by katarinabatina** [comment]
closing in favor of a few specific issues left from the list, thanks for QA @ashfurrow
