### ISSUE TITLE
[Biography] Don’t show section if there is no data at all

### ISSUE THREAD

**Issue by alloy** [artsy/emission#85]
![img_7797](https://cloud.githubusercontent.com/assets/2320/15501474/e8cf4af0-21ad-11e6-9a03-3dd40770a4af.PNG)

**Comment by katarinabatina** [comment]
I wonder if we can hide the about tab all together when there aren't any related artists either.

**Comment by briansw** [comment]
@alloy just one little clarification here: I think we can show the bio section when we have the artist's bioline to display. See below for example:

![screen shot 2016-05-24 at 9 01 14 am](https://cloud.githubusercontent.com/assets/1022172/15504670/16b1b540-218e-11e6-9069-d4df5c0a1e84.png)

**Comment by katarinabatina** [comment]
@briansw does this artist have no related artists at all?

**Comment by briansw** [comment]
correct, I added a separate issue to address that here: https://github.com/artsy/emission/issues/95

**Comment by alloy** [comment]
> I wonder if we can hide the about tab all together when there aren't any related artists either.

Sounds like a good idea then 👍 Would be great if we could find an artist that exhibits this.

Also, would e.g. just the bioline be enough to show the tab, like in the above examples?

**Comment by briansw** [comment]
Personally, I think if only the bioline is present it warrants showing the about tab. 

If we wanted to be fancy we could say the bioline + related artists need to be present to show the tab, but since the next iteration of this view will include partner-submitted bios and exhibition highlights it doesn't seem worth adding in this extra logic. @katarinabatina @alloy what do you think?

**Comment by alloy** [comment]
> the next iteration of this view will include partner-submitted bios and exhibition highlights

Wouldn’t there still be the possibility of _only_ the bioline being available in that scenario? Otherwise I agree with you about keeping it simple for now.

**Comment by briansw** [comment]
@alloy Jack Smith (https://www.artsy.net/artist/jack-smith) is an example artist:
- Has bioline
- Doesn't have bio
- Doesn't have related artists

**Comment by briansw** [comment]
>Wouldn’t there still be the possibility of only the bioline being available in that scenario? Otherwise I agree with you about keeping it simple for now.

You're right, certainly possible, I just imagine much less likely to happen and was trying to avoid needing to update  the about tab visibility logic once these additional pieces of content become part of the page.

**Comment by katarinabatina** [comment]
So I think in the scenario that the artist has no bioline, no bio, no related artists, and no articles then we should get rid of the about tab. 

example artists:
https://www.artsy.net/artist/luis-enrique-toledo-del-rio
https://www.artsy.net/artist/sandra-dal-poggetto

cc @alloy @briansw @sarahscott

**Comment by alloy** [comment]
@katarinabatina Filed #148 for that.
