### ISSUE TITLE
Consignment metadata entry is difficult

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#850]
- [x] Unable to advance to the next field easily
- [x] Done button ends up floating well above the keyboard at times

**Comment by orta** [comment]
You should be able to advance to the next field by pressing return, a visually obvious answer may be something like 

<img width="671" alt="screen shot 2017-11-30 at 10 17 28 am" src="https://user-images.githubusercontent.com/49038/33438070-c7b12036-d5b7-11e7-945b-9be3ef21850c.png">

**Comment by katarinabatina** [comment]
Not a fan of this execution, the return button should say next.

**Comment by katarinabatina** [comment]
Also to not cross wires @mennenia has been looking at this.

**Comment by orta** [comment]
ah, yeah, that's a better move 👍
