### ISSUE TITLE
[RFC] Disable TSLint rule "ordered-imports" 

### ISSUE THREAD

**Issue by damassi** [artsy/emission#861]
### Summary:

Alphabetization, when applied systematically to a code-base, makes code-reading index-like. The more that it's applied in a given project across object-keys, variables, interfaces and imports, the more ones background mind learns to jump to information it is concerned with and discard the rest, which in turn creates less friction, better maintainability, and faster development times. However, this strategy only works if the syntactic structure of a language allows for patterns to emerge. This RFC is an attempt to argue that while the "import-ordering" rule applied by TSLint could work for other languages, it fails to take into account natural read/write patterns in JavaScript and should be abandoned in favor of an ad-hoc, editor-based approach, or no approach at all. 

### Proposal: 

By default TSLint provides a rule that "orders" imports based upon import path, not the object being imported. In practice, a correctly ordered import list looks like:

```javascript
import fonts from "lib/fonts"
import createEnvironment from "lib/relay/createEnvironment"
import React from "react"
import { Dimensions, FlatList, SectionList, TouchableWithoutFeedback, View } from "react-native"
import { StyleSheet, TextStyle } from "react-native"
import { createFragmentContainer, graphql, QueryRenderer, QueryRendererProps } from "react-relay"
import styled from "styled-components/native"
import { LotsByFollowedArtists } from "./Components/LotsByFollowedArtists"
import { SaleList } from "./Components/SaleList"
import { SectionHeader } from "./Components/SectionHeader"
``` 

At a glance, the ordering of this list is non-obvious due to how the heuristic operates: 

1. It requires the developer to read from right-to-left rather than left-to-right, tracking backwards from a variable width import statement that could contain many named import statements, including a default. Inconsistent alignment is difficult on the eyes and obscures the larger pattern
1. It only takes into account the first character of the import path, not the object being imported
  - `lib/fonts` comes before `lib/relay/createEnvironment`, though typically what is most important is _what_ is being used, not _where_ it came from
  - If import declarations were similar to ruby's `require` statement or go's `import`, this would make sense as natural alignment would reveal an alphabetized and orderly tree:

```ruby
require "lib/data/fonts"
require "lib/relay/createEnvironment"
require "react"
require "react-native"
require "react-native"
require "react-relay"
require "styled-components/native"
require "./Components/LotsByFollowedArtists"
require "./Components/SaleList"
require "./Components/SectionHeader"
```
For a side-by-side comparison from above:
```javascript
import fonts from "lib/data/fonts"
import createEnvironment from "lib/relay/createEnvironment"
import React from "react"
import { Dimensions, FlatList, SectionList, TouchableWithoutFeedback, View } from "react-native"
import { StyleSheet, TextStyle } from "react-native"
import { createFragmentContainer, graphql, QueryRenderer, QueryRendererProps } from "react-relay"
import styled from "styled-components/native"
import { LotsByFollowedArtists } from "./Components/LotsByFollowedArtists"
import { SaleList } from "./Components/SaleList"
import { SectionHeader } from "./Components/SectionHeader"
```

3. Some common alphabetization patterns that emerge in code are variable names and object keys:
```javascript
const props = {
  bidError: "Some error",
  formatMoneyWithoutCents: "a function that formats",
  isPendingBid: "nope, not pending",
  mySelectedLotState: "foo/bar/baz",
  onPlaceBidOnLot: "yup!",
  onRegisterToBid: "is registered",
  sale
}

const {
  bidError,
  formatMoneyWithoutCents,
  isPendingBid,
  mySelectedLotState,
  onPlaceBidOnLot,
  onRegisterToBid,
  sale
} = props

const bidError = 
const formatMoneyWithoutCents =
const isPendingBid = 
const mySelectedLotState = 
const onPlaceBidOnLot = 
const onRegisterToBid = 
const sale = 
```

In each instance above, syntax and alignment allow the order of each variable to jump right out. Additionally, an important point is that what is being alphabetized is the "key", not the value, where in the `"ordered-imports"` rule what is alphabetized is the value, not the key. 

4. In practice, since TSLint errors out if things are not alphabetized, its common to see imports  "grouped" and spaced across artificial line-breaks, where the line-break serves to break the alphabetization rule. From Emission, an example: 

```javascript
import React from "react"
import { View } from "react-native"
import ScrollableTabView from "react-native-scrollable-tab-view"
import styled from "styled-components/native"

import SwitchBoard from "lib/NativeModules/SwitchBoard"
import { Router } from "lib/utils/router"

import WorksForYou from "lib/Containers/WorksForYou"
import ForYou from "./Components/ForYou"
import Sales, { SalesRenderer } from "./Components/Sales"

import { ForYouRenderer, WorksForYouRenderer } from "lib/relay/QueryRenderers"
import renderWithLoadProgress from "lib/utils/renderWithLoadProgress"

import DarkNavigationButton from "lib/Components/Buttons/DarkNavigationButton"
import TabBar, { Tab } from "lib/Components/TabBar"
```

While I'm not suggesting that we _don't_ use line-breaks, what I _am_ emphasizing is the additional degree of indirection that the "ordered-imports" rule introduces. With the line-breaks, a developer is now taking control and "ordering" things as s/he sees fit, but taken as a whole the imports are no longer strictly alphabetized, but sub-alphabetized. In practice, this is no better than just having the rule turned off.

 ### Suggestions:

1. The main aim of this RFC is to suggest that good habits can go further than a rule in certain cases, especially if the rule breaks common read/write semantics in a given language
1. That piggybacking on common alphabetization patterns, one sorts by _`key`_ and not by _`value`_ 
1. That the keys (in an object, or the name of a variable thats been assigned a value) are whats used in practice, and so should be emphasized over the value, which is ephemeral and/or an implementation detail
1. That the keys within an import statement are A) the default import; and B) named imports
1. That the import path is is the value, and is secondary to its use throughout code.

Given VSCode's "sort" feature (as well as numerous plugins available to download), there are a number of better options that a dev can take advantage of which will lead to a much more tidy codebase. A couple of examples using "natural sort", from my editor:

```javascript
import Filter from 'components/Filter'
import HelloWorld from 'components/HelloWorld'
import PropTypes from "prop-types"
import React from "react"
import ReactDOM from "react-dom"
``` 

As the simplest example, imports are sorted through "natural sort" and are case sensitive. Adding in some non-class-based functions, an order emerges: 

```javascript
import HelloWorld from 'components/HelloWorld'
import PropTypes from "prop-types"
import React from "react"
import ReactDOM from "react-dom"
import findValue from 'utils/findValue'
import hasName from 'path/to/hasName'
import maxBidderPosition from 'selectors/maxBidderPosition'
import searchIndex from 'utils/searchIndex'
```

A, B, C, then a, b, c. 

Further, if we introduce named imports, the list expands:

```javascript
import PropTypes from "prop-types"
import React from "react"
import ReactDOM from "react-dom"
import hasName from 'path/to/hasName'
import maxBidderPosition from 'selectors/maxBidderPosition'
import searchIndex from 'utils/searchIndex'
import { addItem } from 'utils'
import { cancelBid, hasBid } from 'utils/bids'
import { filterValues } from 'utils/filter'
```

Some examples in the wild:

https://github.com/artsy/prediction/blob/master/src/server.js
https://github.com/artsy/emission/blob/55835f10d22010cdf465a502b633c54c33201bed/src/lib/Scenes/Home/Components/Sales/Components/LotsByFollowedArtists.tsx

Once the pattern is internalized new imports can be inserted right alongside their corresponding type, and future devs looking in will be able to glance at the import list and understand at a glance what is currently being used in a file. Aside from maintainability and orderliness, in terms of aesthetics being able to group default exports together with their kind and named exports with their kind increases readability, while also saying something about whats going on in the code. 

Once again I would like to emphasize what's important is _what_ is being used, not _where_ it comes from; ordering keys is natural, ordering values is not. And all that's needed is to highlight the import list and do `cmd+shift+p > sort`. 

--- 

While the above is just my suggestion as to how to solve the always-nebulous import ordering problem for good, it's secondary to the odd behavior surrounding default behavior of TSLint "ordered-imports", which turning off would solve -- a change I feel that at a minimum would be neutral and not improve or degrade whats currently in place, but free up some space for potential. 

Let me know what y'all think! Since we're employing TypeScript more and more across our code-bases I'm happy this is surfacing now.

**Comment by alloy** [comment]
Indeed the key is what matters and I like the natural sort 👍  I suggest we make our TSLint setup enforce that, rather than completely turning it off, though.

Also, and I know this isn’t what your RFC is about _nor_ do I really have a good objective reason for it right now, I do prefer to have grouped imports for lib files vs project specific files.

**Comment by orta** [comment]
My opinion on a lot of code style things is if we care, we should automate it into more or less how we want.

I don't really have super strong opinions, but I like:

* external modules
* internal modules 


There's a [vscode extension](https://marketplace.visualstudio.com/items?itemName=mike-co.import-sorter) that can automate setting up our imports into something pretty reasonable. Perhaps if we tweak the settings in `.vscode/settings.json` and add it as a default extension we get most of the way?

before:
```js
import React from "react"

import {
  AsyncStorage,
  Dimensions,
  Image,
  NavigatorIOS,
  Route,
  ScrollView,
  TouchableHighlight,
  View,
  ViewProperties,
} from "react-native"
import ConsignmentBG from "../Components/ConsignmentBG"
import { LargeHeadline, Subtitle } from "../Typography"

import { ConsignmentMetadata, ConsignmentSetup, SearchResult } from "../"
import TODO from "../Components/ArtworkConsignmentTodo"

import { Schema, Track, track as _track } from "lib/utils/track"
import { Button, Row } from "../Components/FormElements"
import Artist from "./Artist"
import FinalSubmissionQuestions from "./FinalSubmissionQuestions"
import Location from "./Location"
import Metadata from "./Metadata"
import Provenance from "./Provenance"
import SelectFromPhotoLibrary from "./SelectFromPhotoLibrary"
import Welcome from "./Welcome"

import createSubmission from "../Submission/create"
import updateSubmission from "../Submission/update"
import { uploadImageAndPassToGemini } from "../Submission/uploadPhotoToGemini"

const consignmentsStateKey = "ConsignmentsStoredState"

import SwitchBoard from "../../../NativeModules/SwitchBoard"
```

after (defaults):

```js
import { Schema, Track, track as _track } from 'lib/utils/track';
import React from 'react';
import {
    AsyncStorage, Dimensions, Image, NavigatorIOS, Route, ScrollView, TouchableHighlight, View,
    ViewProperties
} from 'react-native';

import { ConsignmentMetadata, ConsignmentSetup, SearchResult } from '../';
import SwitchBoard from '../../../NativeModules/SwitchBoard';
import TODO from '../Components/ArtworkConsignmentTodo';
import ConsignmentBG from '../Components/ConsignmentBG';
import { Button, Row } from '../Components/FormElements';
import createSubmission from '../Submission/create';
import updateSubmission from '../Submission/update';
import { uploadImageAndPassToGemini } from '../Submission/uploadPhotoToGemini';
import { LargeHeadline, Subtitle } from '../Typography';
import Artist from './Artist';
import FinalSubmissionQuestions from './FinalSubmissionQuestions';
import Location from './Location';
import Metadata from './Metadata';
import Provenance from './Provenance';
import SelectFromPhotoLibrary from './SelectFromPhotoLibrary';
import Welcome from './Welcome';

const consignmentsStateKey = "ConsignmentsStoredState"
```


There's a tonne of tweaks with 

```json
 "importSorter.sortConfiguration.customOrderingRules.rules": [
    {
      "regex": "^@angular",
      "orderLevel": 0,
      "numberOfEmptyLinesAfterGroup": 0
    },
    {
      "regex": "^[@]",
      "orderLevel": 10
    },
    {
      "regex": "^[.]",
      "orderLevel": 30
    }
  ],
```

**Comment by alloy** [comment]
@orta I was thinking that the TSLint rule we’d have for it could autofix them and run on save, or would that be problematic for some reason?

**Comment by orta** [comment]
That can work, the TSLint rules aren't _too_ comprehensive ( and for example we need to tell it that "lib/x" isn't an external module now ) 

https://palantir.github.io/tslint/rules/ordered-imports/

**Comment by orta** [comment]
That said, I've made PRs to TSLint before - and rules are pretty easy to amend and improve

**Comment by orta** [comment]
Both options would automate it, which is what matters to me

**Comment by damassi** [comment]
> Also, and I know this isn’t what your RFC is about nor do I really have a good objective reason for it right now, I do prefer to have grouped imports for lib files vs project specific files.

This is one I've typically followed too until kinda recently. It occurred to me that whether something is a library or even the most basic util import what matters is that it provides a function. Similar to how a path from where it comes from strikes me as an implementation detail, looking at 

```javascript
import { renderToString } from 'react'
import { renderToString } from 'utils/componentHelpers'
import { renderToString } from 'preact'
```
what matters most is the thing -- `renderToString` -- being used and referenced throughout the code, not that it came from `preact` or `react` or my local `utils` folder.

**Comment by alloy** [comment]
Yeah I agree that in reading the overall code in a file what’s most important is just that the function exists, not where it came from.

I think the reason both @orta and I prefer to separate libs and project specific files may have to do with recognising dependencies, both as a signal to possibly a too big dependency being pulled in and to ease debugging, things we do on a very regular basis.

**Comment by orta** [comment]
Yeah, mainly I want external dependencies to be obvious. 

Both [me](http://artsy.github.io/blog/2015/09/18/Cocoa-Architecture-Dependencies/) and alloy (what happened to your blog post?) have pretty strict opinions on them, and keeping track of what is used where helps us know when we can drop them.

**Comment by alloy** [comment]
@orta Did you mean part of [this blog post](http://artsy.github.io/blog/2016/08/15/React-Native-at-Artsy/)?

> Having created a dependency manager, I’m not afraid of some dependencies and don’t subscribe to NIH, but the JavaScript community has gone way overboard for my taste. If, like me, you subscribe to the idea that dependencies are part of your application and you want to be able to know what packages are being pulled in so you can maintain them, then you probably won’t like this aspect very much either.

But in any case, yes we have very strict opinions on dependencies.

**Comment by orta** [comment]
Thought about this a bit more, while looking at the danger source code, where I get more of a free run at an optimal codebase for myself. Looks like my natural preference is 

```js
// External
import * as chalk from "chalk"
import * as hyperLinker from "hyperlinker"
import * as program from "commander"
import * as readlineSync from "readline-sync"
import * as supportsHyperlinks from "supports-hyperlinks"

// Node
import * as fs from "fs"
import { basename } from "path"
import { setTimeout } from "timers"

// Local
import { generateDefaultDangerfile } from "./init/default-dangerfile"
```

**Comment by damassi** [comment]
Sorted by key and much more readable than current typescript rule 😀 I imagine if you had a bunch of named exports those would be similarly grouped as the above

**Comment by orta** [comment]
https://github.com/palantir/tslint/issues/3450 is what we'd need to build, also with the ability to add baseUrl prefixes

**Comment by damassi** [comment]
Have seen the light, closing 🙇

**Comment by alloy** [comment]
Hah, radical! 👌

**Comment by orta** [comment]
I expect one of these days we can trigger this in a pre-commit hook too
