### ISSUE TITLE
[Tab Component] Missing gray rules

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#89]
current:

![image](https://cloud.githubusercontent.com/assets/6482926/15502894/ac9d659a-2184-11e6-9a8a-0bdb7fc14cc0.png)

spec:

![image](https://cloud.githubusercontent.com/assets/6482926/15502923/dce4e3c2-2184-11e6-87d1-f3a7374f114b.png)

**Comment by mennenia** [comment]
Extraction issue, and hence captured [here](https://github.com/artsy/extraction/issues/1). Closing this ticket in favour of the other one :).
