### ISSUE TITLE
[Artist] Initial selected tab should be ‘WORKS’

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#90]
Open artist view, land on about tab, we should adjust this so that the work tab is the default selection when the view is opened.

**Comment by sarahscott** [comment]
This one is deceptively challenging; @alloy  should I try it?

**Comment by katarinabatina** [comment]
If it's easier to make works the first position in the left then feel free to make that change 

Sent with thumbs,
Katarina Batina 
Product Designer
Artsy.net
