### ISSUE TITLE
Add event emitter for `view(Will/Did)Appear` events

### ISSUE THREAD

**Issue by alloy** [artsy/emission#930]
To replace:

* https://github.com/artsy/emission/blob/c83501e8a50a9252982d9ccd1da6005ff0436770/Pod/Classes/ViewControllers/ARComponentViewController.m#L74
* https://github.com/artsy/emission/blob/a91d86646b8745bc21cb80356ae4d8057ae07a60/src/lib/Containers/Inbox.tsx#L37

**Comment by katarinabatina** [comment]
tracked in https://artsyproduct.atlassian.net/browse/IN-22
