### ISSUE TITLE
[RFC] Change `yarn test` to run all types of checks that CI would also run

### ISSUE THREAD

**Issue by alloy** [artsy/emission#934]
More than once I have pushed code where I forgot to run one of the various test tasks. So rather than `yarn test` being a synonym for `yarn jest`, we can have it do `yarn type-check && yarn lint && yarn relay && yarn jest`. Thoughts?

**Comment by alloy** [comment]
In the past we would have had a task like `yarn ci` that would run all of these and would be the task that actually got invoked by CI, but I’m assuming we list them out separately in the Circle config because Circle will then be able to have nice UI for each of those steps (?).

**Comment by sarahscott** [comment]
I think this is a good idea but in my experience, sometimes `yarn ci` passes locally and not in Circle, and I think it's always been linting or prettier-related.

**Comment by alloy** [comment]
@sarahscott To be fair, isn’t that because you maybe don’t have the git commit hook setup to automatically run the linter/prettier?

**Comment by mennenia** [comment]
Yes! 🙌 I agree whole heartedly

**Comment by alloy** [comment]
@sarahscott Maybe there’s a way to also run prettier and rather than write changes exit with a failure status? If so, then that could be added to the `yarn test` task as well, assuming it doesn’t take too long to run.

**Comment by sarahscott** [comment]
@alloy I ran prettier and linter manually, so it wouldn't have been related to a git hook.

**Comment by alloy** [comment]
@sarahscott Next time that it happens, try to nail down how that discrepancy could’ve occurred and then let’s fix it permanently.

**Comment by l2succes** [comment]
No strong opinion, I've been using `yarn ci` for that purpose and since `yarn test` would essentially be the same set of commands minus `yarn prettier-project` I'm fine with it.

**Comment by orta** [comment]
This repo is behind culturally in how we manage git hooks - #905 

In Danger and Peril I run all of the tests/linters before a push, Emission should do this too. Considering how easy/fast it is to run this stuff and how much time it takes to get that eventual feedback after the PR then CI results.

**Comment by orta** [comment]
> I’m assuming we list them out separately in the Circle config because Circle will then be able to have nice UI for each of those steps.

Yep

**Comment by katarinabatina** [comment]
tracked in Jira https://artsyproduct.atlassian.net/browse/IN-15
