### ISSUE TITLE
[Works Tab] Order works by updated_at

### ISSUE THREAD

**Issue by briansw** [artsy/emission#99]
Works should be ordered by updated_at most recent to oldest.

**Comment by sarahscott** [comment]
@alloy or @mzikherman, it looks like metaphysics offers a `partner_updated_at_desc` sort. Is that the correct endpoint for the behavior @briansw described?

**Comment by alloy** [comment]
That does sound like the right one to me, because I _think_ the motivation here is that works who’s metadata is most recently update _by partners_ are the ones that the partners want to most eagerly promote and thus we want to surface those first.

/cc @briansw Is that correct?

**Comment by briansw** [comment]
Exactly

**Comment by mzikherman** [comment]
Yup!

**Comment by sarahscott** [comment]
danke!

![](http://66.media.tumblr.com/f2af962d9e788e99b8d7c7580a6575a6/tumblr_n12jbwy7Ym1tt98tfo2_500.gif)
